const CACHE_NAME = "running-record-app-runtime-2026.10.06.10";
const CACHE_PREFIX = "running-record-app-";
const COMMON_PRECACHE_URLS = [
  "./shared/valueUtilities.js",
  "./shared/recordUtilities.js",
  "./shared/textUtilities.js",
  "./app.js",
  "./core/interpretationBase.js",
  "./core/interpretationCore.js",
  "./core/selfUnderstandingCore.js",
  "./core/selfInterpretationCore.js",
  "./core/appCore.js",
  "./core/rofJConstants.js",
  "./core/rofJAuthorConfirmedScale.js",
  "./core/rofJCore.js",
  "./core/internal/modules.js",
  "./core/internal/platformInfrastructure.js",
  "./core/internal/modelSupport.js",
  "./core/internal/inputSupport.js",
  "./core/internal/recordRepositories.js",
  "./core/internal/primaryModelEngine.js",
  "./core/internal/surfacePresetCatalog.js",
  "./core/internal/primaryInputProcessing.js",
  "./core/internal/primaryModelResults.js",
  "./core/internal/applicationDomain.js",
  "./core/internal/courseRepository.js",
  "./core/internal/restoreInspection.js",
  "./core/internal/backupService.js",
  "./core/internal/publicHelpGuidance.js",
  "./core/internal/recordWorkflow.js",
  "./core/internal/historyWorkflow.js",
  "./core/internal/planPreview.js",
  "./core/internal/planWorkflow.js",
  "./core/internal/evidenceData.js",
  "./core/internal/readingCatalog.js",
  "./core/internal/readingService.js",
  "./core/internal/consultationReport.js",
  "./core/internal/bodyRegionTerminology.js",
  "./core/internal/deterministicConsultation.js",
  "./core/internal/applicationServices.js",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./assets/rof/rof-visual-lowest.png",
  "./assets/rof/rof-visual-low.png",
  "./assets/rof/rof-visual-moderate.png",
  "./assets/rof/rof-visual-high.png",
  "./assets/rof/rof-visual-highest.png",
  "./index.html",
  "./manifest.webmanifest",
  "./screens/shared/aboutScreen.js",
  "./screens/bodyPartDetailScreen.js",
  "./screens/consultationScreen.js",
  "./screens/shared/courseEditorScreen.js",
  "./screens/shared/courseLibraryContext.js",
  "./screens/historyScreen.js",
  "./screens/interpretationRoomScreen.js",
  "./screens/shared/homeScreenSupport.js",
  "./screens/runRouteScreen.js",
  "./screens/bodyTimelineScreen.js",
  "./screens/readingScreen.js",
  "./screens/simulationScreen.js",
  "./screens/planScreen.js",
  "./screens/shared/privacyScreen.js",
  "./screens/shared/termsScreen.js",
  "./screens/recordInputScreen.js",
  "./screens/resultScreen.js",
  "./screens/settingsScreen.js",
  "./screens/screenRegistry.js",
  "./screens/sharedScreenRegistry.js",
  "./screens/shared/supportGuidanceScreen.js",
  "./styles/base.css",
  "./styles/components.css",
  "./styles/layout.css",
  "./styles/screens.css",
  "./styles/responsive.css",
  "./styles/screen-layout-base.css",
  "./styles/home-screen-base.css",
  "./styles/result-screen-base.css",
  "./styles/record-screen-base.css",
  "./styles/body-part-detail-base.css",
  "./styles/history-screen-base.css",
  "./styles/plan-screen-base.css",
  "./styles/simulation-screen-base.css",
  "./styles/consultation-screen-base.css",
  "./styles/course-screen-base.css",
  "./styles/rof-j-visual.css",
  "./styles/rof-j-compact.css",
  "./styles/consultation-share.css",
  "./styles/consultation-share-print.css",
  "./styles/settings-navigation.css",
  "./styles/interpretation-room.css",
  "./styles/self-understanding.css",
  "./styles/interpretation-room-compact.css",
  "./styles/interpretation-loop.css",
  "./styles/interpretation-technical-details.css",
  "./styles/tokens.css",
  "./styles/run-measurement.css",
  "./ui/platformBootstrap.js",
  "./ui/legalAcceptance.js",
  "./ui/bootRecovery.js",
  "./ui/appVersionStatus.js",
  "./ui/readingRuntimeGuard.js",
  "./ui/rofJPresentation.js",
  "./ui/appRouter.js",
  "./ui/deviceLayout.js",
  "./ui/appSettings.js",
  "./ui/appShell.js",
  "./ui/commonComponents.js",
  "./ui/consultationPresentation.js",
  "./ui/coursePresentation.js",
  "./ui/guideContent.js",
  "./ui/historyPresentation.js",
  "./ui/interpretationRoomPresentation.js",
  "./ui/interpretationReferenceKnowledge.js",
  "./ui/bodyRegionVisuals.js",
  "./ui/interactions/browserUtilities.js",
  "./ui/interactions/consultationInteractions.js",
  "./ui/interactions/interpretationRoomInteractions.js",
  "./ui/interactions/readingInteractions.js",
  "./ui/interactions/courseInteractions.js",
  "./ui/interactions/formUtilities.js",
  "./ui/interactions/gradeDomainConfirmation.js",
  "./ui/interactions/historyInteractions.js",
  "./ui/interactions/planInteractions.js",
  "./ui/interactions/simulationInteractions.js",
  "./ui/interactions/gpxAnalysisInteractions.js",
  "./ui/interactions/recordInputInteractions.js",
  "./ui/interactions/settingsInteractions.js",
  "./ui/personalContextPresentation.js",
  "./ui/recordEmbeddedSubflows.js",
  "./ui/recordInputWorkspace.js",
  "./ui/flowSessionState.js",
  "./ui/gpxLocalAnalysis.js",
  "./ui/runMeasurementCore.js",
  "./ui/runMeasurementMap.js",
  "./ui/runMeasurementNotifications.js",
  "./ui/runMeasurementState.js",
  "./ui/interactions/runRouteInteractions.js",
  "./ui/interactions/bodyTimelineInteractions.js",
  "./ui/recordPresentation.js",
  "./ui/restorePreviewPresentation.js",
  "./ui/screenArchitecture.js",
  "./ui/screenInteractions.js",
  "./ui/sharedScreenInteractionBinders.js",
  "./ui/screenTutorial.js",
  "./ui/shellInteractions.js",
  "./ui/subjectivePresentation.js",
  "./ui/uiMotion.js",
  "./ui/platformStyles.js",
];

const MOBILE_PLATFORM_URLS = [
  "./ui/interactions/mobileHomeInteractions.js",
  "./ui/interactions/mobileHomeLayoutState.js",
  "./ui/interactions/mobileHomeEditPresentation.js",
  "./ui/interactions/mobileHomeGridModel.js",
  "./ui/interactions/mobileQuickToolsInteractions.js",
  "./ui/interactions/mobilePhotoMemoInteractions.js",
  "./ui/interactions/mobilePaceCalculatorInteractions.js",
  "./ui/interactions/mobilePlanInteractions.js",
  "./ui/interactions/mobileSimulationInteractions.js",
  "./ui/interactions/mobileResultInteractions.js",
  "./ui/interactions/mobileRecordInputInteractions.js",
  "./ui/interactions/mobileCourseInteractions.js",
  "./ui/interactions/mobileBodyPartDetailInteractions.js",
  "./ui/mobileRunMeasurementEnergy.js",
  "./ui/mobileRunMeasurementAutoRecord.js",
  "./ui/interactions/mobileRunMeasurementInteractions.js",
  "./core/mobileWalkJogCore.js",
  "./core/internal/mobileWalkJogSpeedModel.js",
  "./screens/mobile/achievementsScreen.js",
  "./screens/mobile/courseLibraryScreen.js",
  "./screens/mobile/courseEditorScreen.js",
  "./screens/mobile/homeScreen.js",
  "./screens/mobile/resultScreen.js",
  "./screens/mobile/historyScreen.js",
  "./screens/mobile/recordInputScreen.js",
  "./screens/mobile/bodyPartDetailScreen.js",
  "./screens/mobile/interpretationRoomScreen.js",
  "./screens/mobile/readingScreen.js",
  "./screens/mobile/settingsScreen.js",
  "./screens/mobile/planScreen.js",
  "./screens/mobile/simulationScreen.js",
  "./screens/mobile/runMeasurementScreen.js",
  "./screens/mobile/gpxAnalysisScreen.js",
  "./screens/mobile/quickToolsScreen.js",
  "./screens/mobile/photoMemoScreen.js",
  "./screens/mobile/paceCalculatorScreen.js",
  "./screens/mobileScreenRegistry.js",
  "./styles/mobile-screen-layouts.css",
  "./styles/mobile-home.css",
  "./styles/mobile-home-editing.css",
  "./styles/mobile-home-ios-editing.css",
  "./styles/mobile-home-three-row.css",
  "./styles/mobile-record.css",
  "./styles/mobile-run-measurement.css",
  "./styles/mobile-run-measurement-ergonomics.css",
  "./styles/mobile-walk-jog.css",
  "./styles/mobile-walk-jog-records.css",
  "./styles/mobile-walk-jog-history.css",
  "./styles/mobile-app-screens.css",
  "./styles/mobile-quick-tools.css",
  "./styles/mobile-pace-calculator.css",
  "./styles/mobile-navigation-unification.css",
  "./styles/mobile-usability.css",
  "./styles/mobile-course.css",
  "./styles/mobile-onboarding.css",
  "./styles/mobile-achievements.css",
  "./styles/mobile-accessibility.css",
  "./styles/mobile-home-gesture.css",
  "./styles/mobile-achievements-responsive.css",
  "./styles/mobile-run-lab.css",
  "./styles/mobile-body-timeline.css",
  "./styles/mobile-run-route.css",
  "./styles/mobile-insights.css",
  "./styles/mobile-about.css",
  "./styles/mobile-home-experience.css",
  "./styles/mobile-home-responsive.css",
  "./styles/mobile-result-region-sheet.css",
  "./styles/mobile-body-part-detail.css",
  "./styles/mobile-history.css",
  "./styles/mobile-home-viewport-balance.css",
  "./styles/consultation-share-mobile.css",
  "./styles/mobile-components-responsive.css",
  "./styles/mobile-consultation-share-responsive.css",
  "./styles/mobile-interpretation-loop-responsive.css",
  "./styles/mobile-interpretation-room-compact-responsive.css",
  "./styles/mobile-interpretation-room-responsive.css",
  "./styles/mobile-interpretation-technical-details-responsive.css",
  "./styles/mobile-layout-responsive.css",
  "./styles/mobile-responsive.css",
  "./styles/mobile-rof-j-compact-responsive.css",
  "./styles/mobile-rof-j-visual-responsive.css",
  "./styles/mobile-run-measurement-responsive.css",
  "./styles/mobile-screens-responsive.css",
  "./styles/mobile-self-understanding-responsive.css",
  "./styles/mobile-self-understanding.css",
  "./ui/mobileRunFingerprint.js",
  "./ui/mobileVersionStatus.js",
  "./ui/mobileRofJPresentation.js",
  "./ui/mobileAppRuntime.js",
  "./ui/mobileAppShell.js",
  "./ui/mobileRuntimeEntry.js",
  "./ui/mobileAchievements.js",
  "./ui/mobileInsights.js",
  "./ui/mobileHomeExperience.js",
  "./ui/mobileMeasurementRecordAutofill.js",
  "./ui/mobileHomeDefaultLayout.js",
  "./ui/mobileHomeGridUtilities.js",
  "./ui/mobileDateUtilities.js",
  "./ui/mobileStorageUtilities.js",
  "./ui/mobileMeasurementDomUtilities.js",
  "./ui/mobileNavigationPolicy.js",
  "./ui/mobileWalkJogMeasurementWiring.js",
  "./ui/mobileWalkJogGpsQuality.js",
  "./ui/mobileWalkJogGpsQualityUi.js",
  "./ui/mobileWalkJogCopyGuard.js",
  "./ui/mobileWalkJogRecordStore.js",
  "./ui/mobileWalkJogSaveHistoryLink.js",
  "./ui/mobileWalkJogHistoryUi.js",
  "./ui/mobileWalkJogGpsQualityHistoryGuard.js",
  "./ui/mobileHomePageCapacity.js",
  "./ui/mobileHomeHub.js",
  "./ui/mobileOnboarding.js",
  "./ui/mobileHomeDropCoordinator.js",
  "./ui/mobileHomeWidgetIconSwap.js",
  "./ui/iosHomeEditScroll.js",
  "./ui/mobileHomeEditScroll.js",
  "./ui/mobileHomeReturnTransition.js",
  "./ui/mobileQuickToolsStore.js",
  "./ui/mobilePhotoMemoStore.js",
  "./ui/mobileScreenInteractionBinders.js",
];

const DESKTOP_PLATFORM_URLS = [
  "./screens/desktop/courseLibraryScreen.js",
  "./screens/desktop/courseEditorScreen.js",
  "./screens/desktop/homeScreen.js",
  "./screens/desktop/historyScreen.js",
  "./screens/desktop/resultScreen.js",
  "./screens/desktop/bodyPartDetailScreen.js",
  "./screens/desktop/interpretationRoomScreen.js",
  "./screens/desktop/readingScreen.js",
  "./screens/desktop/settingsScreen.js",
  "./screens/desktop/planScreen.js",
  "./screens/desktop/simulationScreen.js",
  "./screens/desktop/recordInputScreen.js",
  "./screens/desktop/gpxAnalysisScreen.js",
  "./screens/desktop/runMeasurementScreen.js",
  "./screens/desktop/moreScreen.js",
  "./screens/desktopScreenRegistry.js",
  "./styles/desktop-history-state.css",
  "./styles/desktop-course.css",
  "./styles/desktop-foundation.css",
  "./styles/desktop-screen-layouts.css",
  "./styles/desktop-ui-tokens.css",
  "./styles/desktop-first-use.css",
  "./styles/desktop-history.css",
  "./styles/desktop-simulation.css",
  "./styles/desktop-body-timeline.css",
  "./styles/desktop-interpretation-layout.css",
  "./styles/desktop-information.css",
  "./styles/desktop-consultation.css",
  "./styles/desktop-theme.css",
  "./styles/desktop-empty-states.css",
  "./styles/desktop-home-layout.css",
  "./styles/desktop-interpretation-regions.css",
  "./styles/desktop-course-editor.css",
  "./styles/desktop-actions.css",
  "./styles/desktop-about.css",
  "./styles/desktop-settings.css",
  "./styles/desktop-unification.css",
  "./styles/desktop-interpretation-details.css",
  "./styles/desktop-components-responsive.css",
  "./styles/desktop-consultation-share-responsive.css",
  "./styles/desktop-interpretation-loop-responsive.css",
  "./styles/desktop-interpretation-room-compact-responsive.css",
  "./styles/desktop-layout-responsive.css",
  "./styles/desktop-responsive.css",
  "./styles/desktop-rof-j-compact-responsive.css",
  "./styles/desktop-rof-j-visual-responsive.css",
  "./styles/desktop-run-measurement-responsive.css",
  "./styles/desktop-screens-responsive.css",
  "./styles/desktop-self-understanding-responsive.css",
  "./styles/desktop-self-understanding.css",
  "./styles/desktop-settings-navigation-responsive.css",
  "./ui/desktopRofJPresentation.js",
  "./ui/desktopAppRuntime.js",
  "./ui/desktopAppShell.js",
  "./ui/desktopRuntimeEntry.js",
  "./ui/desktopFirstUse.js",
  "./ui/desktopHomeWorkspace.js",
  "./ui/interactions/desktopResultInteractions.js",
  "./ui/interactions/desktopRecordInputInteractions.js",
  "./ui/desktopScreenInteractionBinders.js",
  "./ui/desktopHistoryWorkspace.js",
  "./ui/desktopBodyTimelineWorkspace.js",
];

const PLATFORM_URLS = Object.freeze({
  mobile: MOBILE_PLATFORM_URLS,
  desktop: DESKTOP_PLATFORM_URLS,
});

const RUNTIME_URLS = [...COMMON_PRECACHE_URLS, ...MOBILE_PLATFORM_URLS, ...DESKTOP_PLATFORM_URLS];
const RUNTIME_PATHS = new Set(RUNTIME_URLS.map((path) => new URL(path, self.location).pathname));

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(COMMON_PRECACHE_URLS))
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
        .map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(fetch(request, { cache: "no-store" }).catch(() => caches.match("./index.html")));
    return;
  }

  if (!RUNTIME_PATHS.has(url.pathname)) return;
  event.respondWith(
    caches.open(CACHE_NAME).then(async (cache) => {
      try {
        const response = await fetch(new Request(request, { cache: "no-store" }));
        if (response.ok && response.type === "basic") {
          event.waitUntil(cache.put(request, response.clone()));
        }
        return response;
      } catch {
        return (await cache.match(request, { ignoreSearch: true })) || Response.error();
      }
    })
  );
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    self.skipWaiting();
    return;
  }

  if (event.data?.type !== "CACHE_PLATFORM") return;
  const platformUrls = PLATFORM_URLS[event.data?.platform];
  if (!platformUrls) return;
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(platformUrls))
  );
});
