import test from 'node:test';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { createApplicationServices, createMemoryStorage } from '../core/appCore.js';
import { internalModules } from '../core/internal/modules.js';

// Actual synthetic snapshot generated by the V2.43 original running engine,
// before coefficient or model-version changes. It contains no user data.
const fixture = JSON.parse(fs.readFileSync(new URL('./fixtures/a03ActualHistoricV30Backup.json', import.meta.url), 'utf8'));
const old = fixture.originalResult;
function app() { return createApplicationServices({storage:createMemoryStorage()}); }

function restore(s) {
  const check = s.storage.backup.validateBackupSnapshot(fixture.snapshot);
  assert.equal(check.canRestore,true,JSON.stringify(check.issues));
  const result = s.storage.backup.restoreBackupText(JSON.stringify(fixture.snapshot));
  assert.equal(result.ok,true,JSON.stringify(result));
}

test('original v3.0 backup is imported byte-for-byte semantically and remains available read-only', () => {
  const s=app(); restore(s);
  const before=s.storage.modelResultsRegionalV2.loadForRecord(old.record_id);
  assert.deepEqual(before,[old]);
  const restoredRecord=s.storage.records.loadAll().find(x=>x.id===old.record_id);
  assert.equal(restoredRecord.regionalModelSnapshot.snapshotId,'PRIMARY_REGIONAL_REFERENCE100_V3');
  assert.equal(restoredRecord.regionalModelSnapshot.modelVersion,'runload-primary-regional-reference100-v3.0');
  const experience=s.workflows.records.loadExperience(old.record_id);
  assert.deepEqual(experience.regionalV2ResultRecord,old);
  assert.equal(experience.regionalSemanticState,'REFERENCE100_V3_HISTORIC_READ_ONLY');
  assert.equal(experience.regionalV2Recovery,null);
  assert.equal(s.storage.modelResultsRegionalV2.loadForRecord(old.record_id).length,1);
});

test('original v3.0 and scientifically revised v3.1 yield distinct IDs, values and noncomparable signatures', () => {
  const s=app(); restore(s);
  const record=s.storage.records.loadAll().find(x=>x.id===old.record_id);
  const feedback=s.storage.subjectiveFeedback.loadAll().find(x=>x.recordId===old.record_id);
  assert.equal(s.workflows.records.saveRecordAndFeedback({...record,updatedAt:record.updatedAt||record.createdAt},feedback).ok,true);
  const both=s.storage.modelResultsRegionalV2.loadForRecord(old.record_id);
  assert.equal(both.length,2);
  assert.deepEqual(both.find(x=>x.model_version===old.model_version),old);
  const newer=both.find(x=>x.model_version==='runload-primary-regional-reference100-v3.1');
  const upgradedRecord=s.storage.records.loadAll().find(x=>x.id===old.record_id);
  assert.equal(upgradedRecord.regionalModelSnapshot.snapshotId,'PRIMARY_REGIONAL_REFERENCE100_V3_1');
  assert.equal(upgradedRecord.regionalModelSnapshot.modelVersion,'runload-primary-regional-reference100-v3.1');
  assert.ok(newer);assert.notEqual(newer.id,old.id);
  assert.notEqual(newer.result.regions[0].value,old.result.regions[0].value);
  assert.notEqual(newer.result.regions[7].value,old.result.regions[7].value);
  const compare=internalModules.primaryRegionalResultService.comparePrimaryRegionalV2Signatures(
    old.comparison_signatures['BA-DISP-014'],newer.comparison_signatures['BA-DISP-014']);
  assert.equal(compare.directDeltaAllowed,false);
  assert.equal(compare.status,'INCOMPATIBLE');
  assert.equal(s.storage.modelResultsRegionalV2.findLatestForRecord(old.record_id).id,newer.id);
  assert.equal(s.storage.modelResultsRegionalV2.latestByRecord().get(old.record_id).id,newer.id);
  assert.equal(s.workflows.records.loadExperience(old.record_id).regionalV2ResultRecord.id,newer.id);
});

test('historic records with invalid route evidence remain archived, not silently recalculated as v3.1', () => {
  const s=app();restore(s);
  const bad=structuredClone(old);bad.result.regions[0].routeTrace=[];
  assert.equal(s.storage.modelResultsRegionalV2.saveAll([bad]).ok,true);
  const exp=s.workflows.records.loadExperience(old.record_id);
  assert.equal(exp.regionalV2ResultRecord,null);
  assert.equal(exp.regionalV2Recovery.status,'HISTORIC_ARCHIVE_UNAVAILABLE');
  assert.equal(s.storage.modelResultsRegionalV2.loadForRecord(old.record_id)[0].model_version,old.model_version);
  assert.equal(s.storage.modelResultsRegionalV2.loadForRecord(old.record_id)[0].result.regions[0].routeTrace.length,0);
});
