import assert from "node:assert/strict";
import fs from "node:fs";
const read=(path)=>fs.readFileSync(path,"utf8");
const js=read("ui/desktopBodyTimelineEnhancement.js");
const css=read("styles/desktop-body-timeline.css");
const index=read("index.html");
const worker=read("service-worker.js");
const version=read("ui/appVersionStatus.js");
assert.match(version,/APP_VERSION = "\d{4}\.\d{2}\.\d{2}\.\d+"/);
assert.match(worker,/running-record-app-runtime-\d{4}\.\d{2}\.\d{2}\.\d+/);
assert.match(index,/desktop-body-timeline\.css/);
assert.match(index,/desktopBodyTimelineEnhancement\.js/);
assert.ok(worker.includes('"./styles/desktop-body-timeline.css"'));
assert.ok(worker.includes('"./ui/desktopBodyTimelineEnhancement.js"'));
assert.match(js,/matchesMobileLayout/);
assert.match(js,/data-desktop-body-timeline-selector/);
assert.match(js,/aria-selected/);
assert.match(js,/ArrowLeft/);
assert.match(js,/dataset\.pcSelected/);
assert.match(js,/restoreMobileTimeline/);
assert.match(css,/width: min\(100%, 88rem\)/);
assert.match(css,/grid-template-columns: minmax\(14\.5rem, 18rem\) minmax\(0, 1fr\)/);
assert.match(css,/body-timeline-map__region\[data-direction="above"\]/);
assert.match(css,/var\(--color-model\)/);
assert.doesNotMatch(css,/var\(--model\)/);
assert.match(css,/body-timeline-dots/);
console.log("desktopBodyTimeline.test.mjs: PASS");
