import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=(f)=>fs.readFileSync(path.join(root,f),'utf8');
const index=read('index.html');
const worker=read('service-worker.js');
const presentation=read('ui/interpretationRoomPresentation.js');
assert.match(index,/desktop-interpretation-layout\.css/);
assert.ok(worker.includes('"./styles/desktop-interpretation-layout.css"'));
assert.match(index,/interpretation-technical-details\.css/);
assert.ok(worker.includes('"./styles/interpretation-technical-details.css"'));
assert.match(presentation,/v53-room--pc/);
assert.match(presentation,/v53-room--mobile/);
assert.match(presentation,/今回を見比べる/);
assert.doesNotMatch(presentation,/return renderDesktopInterpretationWorkspace\(/);
console.log(JSON.stringify({suite:'Desktop Interpretation Layout',total:1,passed:1,failed:0,status:'PASS'}));
