import assert from "node:assert/strict";
import fs from "node:fs";

const read=(path)=>fs.readFileSync(path,"utf8");
const desktopCss=read("styles/desktop-consultation.css");
const shareCss=read("styles/consultation-share.css");
const desktopShareCss=read("styles/desktop-consultation-share-responsive.css");
const unified=read("styles/desktop-unification.css");
const screen=read("screens/consultationScreen.js");
const index=read("index.html");
const platformStyles=read("ui/platformStyles.js");
const worker=read("service-worker.js");
const version=read("ui/appVersionStatus.js");

assert.match(version,/APP_VERSION = "\d{4}\.\d{2}\.\d{2}\.\d+"/);
assert.match(worker,/running-record-app-runtime-\d{4}\.\d{2}\.\d{2}\.\d+/);
assert.match(platformStyles,/desktop-consultation\.css/);
assert.match(index,/consultation-share\.css/);
assert.ok(worker.includes('"./styles/desktop-consultation.css"'));
assert.ok(worker.includes('"./styles/consultation-share.css"'));
assert.match(screen,/data-share-prep/);
assert.match(screen,/share-purpose-step/);
assert.match(screen,/share-source-list/);
assert.match(screen,/share-document-stage/);
assert.match(screen,/share-output-actions/);
assert.match(screen,/完成資料を確認/);
assert.match(desktopCss,/@media \(min-width: 69rem\)/);
assert.match(shareCss,/Consultation share preparation uses the current four-step flow/);
assert.match(desktopShareCss,/grid-template-areas: none !important/);
assert.match(desktopShareCss,/grid-template-columns: repeat\(3, minmax\(0, 1fr\)\) !important/);
assert.match(screen,/share-input-stack/);
assert.match(unified,/max-width: 77rem !important/);
assert.match(unified,/share-input-stack[\s\S]*grid-area: inputs !important/);
assert.match(unified,/share-document-step[\s\S]*position: sticky !important/);
assert.match(unified,/share-document-stage:not\(\.is-expanded\)[\s\S]*max-height: 30rem !important[\s\S]*overflow: auto !important/);
assert.match(unified,/share-document-stage:not\(\.is-expanded\)[\s\S]*share-sheet-page ~ \.share-sheet-page[\s\S]*display: none !important/);
assert.doesNotMatch(unified,/share-document-stage\.is-expanded[\s\S]{0,220}share-sheet-page[\s\S]{0,120}display: block !important/);
assert.match(unified,/share-sheet-head h1[\s\S]*white-space: normal !important/);
assert.match(unified,/share-sheet-head dl[\s\S]*width: 100% !important/);
assert.match(shareCss,/@media print/);

console.log("desktopConsultation.test.mjs: PASS");
