import assert from "node:assert/strict";
import fs from "node:fs";
const read=(path)=>fs.readFileSync(path,"utf8");
const css=read("styles/desktop-simulation-v40.css");
const index=read("index.html");
const worker=read("service-worker.js");
const screen=read("screens/simulationScreen.js");
const version=read("ui/appVersionStatus.js");
assert.match(version,/APP_VERSION = "2026\.10\.01\.\d+"/);
assert.match(worker,/running-record-app-runtime-2026\.10\.01\.\d+/);
assert.match(index,/desktop-simulation-v40\.css/);
assert.ok(worker.includes('"./styles/desktop-simulation-v40.css"'));
assert.match(screen,/condition-compare-workspace/);
assert.match(screen,/condition-snapshot previous/);
assert.match(screen,/condition-snapshot assumed/);
assert.match(css,/width: min\(100%, 88rem\)/);
assert.match(css,/--pc-type-title/);
assert.match(css,/condition-compare-overview-grid/);
assert.match(css,/minmax\(21rem,22rem\)/);
console.log("desktopSimulationV40.test.mjs: PASS");
