import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=(f)=>fs.readFileSync(path.join(root,f),'utf8');
const index=read('index.html');
const platformStyles=read('ui/platformStyles.js');
const worker=read('service-worker.js');
const presentation=read('ui/interpretationRoomPresentation.js');
const desktopScreen=read('screens/desktop/interpretationRoomScreen.js');
const mobileScreen=read('screens/mobile/interpretationRoomScreen.js');
assert.match(platformStyles,/desktop-interpretation-layout\.css/);
assert.ok(worker.includes('"./styles/desktop-interpretation-layout.css"'));
assert.match(index,/interpretation-technical-details\.css/);
assert.ok(worker.includes('"./styles/interpretation-technical-details.css"'));
assert.match(presentation,/interpretation-flow-room--wide/);
assert.match(presentation,/interpretation-flow-room--compact/);
assert.match(desktopScreen,/compactLayout: false/);
assert.match(mobileScreen,/compactLayout: true/);
assert.match(presentation,/今回を見比べる/);
assert.doesNotMatch(presentation,/return renderDesktopInterpretationWorkspace\(/);
console.log(JSON.stringify({suite:'Desktop Interpretation Layout',total:1,passed:1,failed:0,status:'PASS'}));
