import assert from "node:assert/strict";
import fs from "node:fs";

const editor=fs.readFileSync("screens/courseEditorScreen.js","utf8");
const library=fs.readFileSync("screens/courseLibraryScreen.js","utf8");
const gpx=fs.readFileSync("screens/mobile/gpxAnalysisScreen.js","utf8");
const interactions=fs.readFileSync("ui/interactions/courseInteractions.js","utf8");
const css=fs.readFileSync("styles/mobile-course-v16.css","utf8");
const index=fs.readFileSync("index.html","utf8");
const version=fs.readFileSync("ui/appVersionStatus.js","utf8");
const worker=fs.readFileSync("service-worker.js","utf8");
const history=fs.readFileSync("docs/MOBILE_RELEASE_HISTORY.md","utf8");

assert.match(editor,/matchesMobileLayout\(\)\?renderMobileCourseEditor/);
assert.match(editor,/data-course-grade-family="PROFILE"/);
assert.match(editor,/data-course-grade-method-panel/);
assert.match(editor,/surface-mix-grid/);
assert.match(editor,/data-course-summary-name/);
const mobileEditor=editor.slice(editor.indexOf("function renderMobileCourseEditor"),editor.indexOf("function renderDesktopCourseEditor"));
assert.ok(!mobileEditor.includes("gpx-inline"),"mobile editor must not duplicate the GPX route");
assert.match(library,/course-mobile-gpx-link/);
assert.match(gpx,/GPXから坂道を入力/);
assert.match(interactions,/function updateMobileSummary/);
assert.match(interactions,/data-course-grade-family/);
assert.match(css,/Smartphone course-setting refinement v16/);
assert.match(css,/surface-mix-item > span:first-child/);
assert.match(index,/mobile-course-v16\.css/);
const versionMatch=version.match(/APP_VERSION = "(\d{4}\.\d{2}\.\d{2})\.(\d+)"/);
assert.ok(versionMatch,"current release version must remain explicit");
const versionTuple = versionMatch[1].split(".").map(Number).concat(Number(versionMatch[2]));
const minimumV16 = [2026,9,30,16];
const atLeastV16 = versionTuple.some((value,index)=>value>minimumV16[index] && versionTuple.slice(0,index).every((part,i)=>part===minimumV16[i])) || versionTuple.every((value,index)=>value===minimumV16[index]);
assert.ok(atLeastV16,"mobile v16 behavior must remain present in v2026.09.30.16 or later releases");
assert.ok(worker.includes(`running-record-app-runtime-${versionMatch[1]}.${versionMatch[2]}`),"service-worker release cache must match the current explicit app version");
assert.match(worker,/mobile-course-v16\.css/);
assert.match(history,/APP v2026\.09\.30\.16 — Screenshot-guided Course Refinement 1/);
console.log("mobileCourseRefineV16.test.mjs: PASS");
