import assert from "node:assert/strict";
import fs from "node:fs";
const screen=fs.readFileSync(new URL("../screens/mobile/runMeasurementScreen.js", import.meta.url),"utf8");
const interactions=fs.readFileSync(new URL("../ui/interactions/runMeasurementInteractions.js", import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../styles/mobile-run-measurement-ergonomics.css", import.meta.url),"utf8");
const version=fs.readFileSync(new URL("../ui/appVersionStatus.js", import.meta.url),"utf8");
const worker=fs.readFileSync(new URL("../service-worker.js", import.meta.url),"utf8");
const currentVersion=version.match(/APP_VERSION = "([^"]+)"/)?.[1]||"";
assert.match(currentVersion,/^\d{4}\.\d{2}\.\d{2}\.\d+$/);
assert.ok(worker.includes(`running-record-app-runtime-${currentVersion}`));
assert.match(screen,/if \(!matchesMobileLayout\(\)\) return desktopUnavailable\(\)/);
assert.match(screen,/data-action="toggle-measurement-map"/);
assert.match(screen,/run-measurement-active__secondary/);
assert.match(screen,/run-measurement-post__facts--primary/);
assert.match(screen,/run-measurement-post__auto-details/);
assert.match(screen,/data-measurement-fatigue-comparison/);
assert.match(screen,/記録を完成する/);
assert.match(interactions,/function setGpsStatus/);
assert.match(interactions,/function gpsQuality/);
assert.match(interactions,/function toggleMapPanel/);
assert.match(interactions,/走る前.*走った後/);
assert.match(css,/Mobile Phase 7/);
assert.match(css,/position: sticky/);
assert.ok(css.includes('data-gps-quality="good"'));
assert.match(css,/run-measurement-post__auto-details/);
assert.match(css,/run-measurement-post__facts\.run-measurement-post__facts--secondary/);
console.log("mobileOnlyImprovementPhase7.test.mjs: PASS");
