import assert from 'node:assert/strict';
import { bindMobileQuickTool } from '../ui/interactions/mobileQuickToolsInteractions.js';
import { addMobileQuickToolEntry, loadMobileQuickTools, removeMobileQuickToolEntry } from '../ui/mobileQuickToolsStore.js';
import { writeMobileLocalJson } from '../ui/mobileStorageUtilities.js';

const KEY = 'running-record-mobile-quick-tools-v1';
const results=[];
async function check(id, fn) { try { await fn(); results.push({id,status:'PASS'}); } catch (e) {results.push({id,status:'FAIL',error:String(e?.stack||e)});} }
function useStorage(storage, cb) {const old=Object.getOwnPropertyDescriptor(globalThis,'localStorage'); Object.defineProperty(globalThis,'localStorage',{configurable:true,writable:true,value:storage}); try{return cb();}finally{if(old)Object.defineProperty(globalThis,'localStorage',old);else delete globalThis.localStorage;}}
function storageMock(initial={}) { const values=new Map(Object.entries(initial));return {getItem:k=>values.get(k)??null,setItem(k,v){values.set(k,String(v));},removeItem:k=>values.delete(k),values};}
await check('MISSING-STORAGE-FAILS-WITHOUT-CLAIMING-SUCCESS',()=>useStorage(undefined,()=>{assert.equal(writeMobileLocalJson(KEY,{}),false); assert.equal(addMobileQuickToolEntry('departure', {checks:['水分']}),null);}));
await check('QUOTA-ERROR-DOES-NOT-MUTATE-OLD-SNAPSHOT',()=>{const original=JSON.stringify({departureChecks:[{id:'old',checks:['鍵']}],quickNotes:[{id:'legacy',next:'確認'}]});const storage={getItem:k=>k===KEY?original:null,setItem(){throw new Error('QuotaExceededError');}}; useStorage(storage,()=>{assert.equal(addMobileQuickToolEntry('departure',{checks:['水分']}),null);assert.equal(storage.getItem(KEY),original);});});
await check('RETIRED-MEMOS-REMAIN-IN-OLD-STORAGE',()=>{const old={locationNotes:[{id:'l',note:'坂'}],quickNotes:[{id:'q',next:'水分'}],gearNotes:[{id:'g',shoes:'x'}],fuelNotes:[{id:'f',amount:'水'}],departureChecks:[{id:'d',checks:['鍵']}]};const storage=storageMock({[KEY]:JSON.stringify(old)});useStorage(storage,()=>{const s=loadMobileQuickTools();for(const k of Object.keys(old)) assert.deepEqual(s[k],old[k].map(e=>({createdAt:'',...e})));assert.equal(addMobileQuickToolEntry('departure',{checks:['水分']})?.checks[0],'水分');for(const k of ['locationNotes','quickNotes','gearNotes','fuelNotes']) assert.equal(JSON.parse(storage.getItem(KEY))[k].length,1);});});
await check('RETIRED-ROUTE-SUBMIT-IS-NOOP',()=>{const old={document:Object.getOwnPropertyDescriptor(globalThis,'document'),FormData:Object.getOwnPropertyDescriptor(globalThis,'FormData'),localStorage:Object.getOwnPropertyDescriptor(globalThis,'localStorage')};const listeners={};const status={textContent:'',dataset:{}};const form={dataset:{mobileToolForm:'quick'}};const root={querySelector(sel){return sel==='[data-mobile-tool-form]'?form:sel==='[data-mobile-tool-form-status]'?status:null;},addEventListener(k,v){listeners[k]=v;},removeEventListener(k){delete listeners[k];}};const storage=storageMock();try{globalThis.document={querySelector:()=>root};globalThis.localStorage=storage;globalThis.FormData=class{constructor(){} get(){return null;}getAll(){return []}};let rerenders=0;const cleanup=bindMobileQuickTool({rerender(){rerenders++}});listeners.submit({target:form,preventDefault(){}});assert.equal(rerenders,0);assert.equal(storage.getItem(KEY),null);cleanup();}finally{for(const [k,d] of Object.entries(old)){if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];}}});
await check('DEPARTURE-ENTRY-CAN-BE-REMOVED-WITHOUT-ERASING-HISTORICAL-MEMOS',()=>{const old={quickNotes:[{id:'q',next:'legacy'}],departureChecks:[{id:'d',checks:['鍵']}]};const storage=storageMock({[KEY]:JSON.stringify(old)});useStorage(storage,()=>{assert.equal(removeMobileQuickToolEntry('departure','d'),true);assert.equal(loadMobileQuickTools().departureChecks.length,0);assert.equal(loadMobileQuickTools().quickNotes[0].next,'legacy');});});
const failed=results.filter(x=>x.status==='FAIL');console.log(JSON.stringify({suite:'Mobile Quick Tools Retirement and Storage Boundary',total:results.length,passed:results.length-failed.length,failed:failed.length,results},null,2));if(failed.length)process.exitCode=1;
