import assert from "node:assert/strict";
import fs from "node:fs";
const screen=fs.readFileSync(new URL("../screens/mobile/runMeasurementScreen.js", import.meta.url),"utf8");
const desktopRegistry=fs.readFileSync(new URL("../screens/desktopScreenRegistry.js", import.meta.url),"utf8");
const mobileRegistry=fs.readFileSync(new URL("../screens/mobileScreenRegistry.js", import.meta.url),"utf8");
const interactions=fs.readFileSync(new URL("../ui/interactions/runMeasurementInteractions.js", import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../styles/mobile-run-measurement-ergonomics.css", import.meta.url),"utf8");
assert.doesNotMatch(desktopRegistry,/run-measurement/);
assert.match(mobileRegistry,/"run-measurement": renderRunMeasurementScreen/);
assert.doesNotMatch(screen,/matchesMobileLayout|desktopUnavailable|run-measurement-unavailable/);
assert.match(screen,/data-action="toggle-measurement-map"/);
assert.match(screen,/run-measurement-active__secondary/);
assert.match(screen,/run-measurement-post__facts--primary/);
assert.match(screen,/run-measurement-post__auto-details/);
assert.match(screen,/data-measurement-fatigue-comparison/);
assert.match(screen,/記録を完成する/);
assert.match(interactions,/function setGpsStatus/);
assert.match(interactions,/function gpsQuality/);
assert.match(interactions,/function toggleMapPanel/);
assert.match(interactions,/走る前.*走った後/);
assert.match(css,/position: sticky/);
assert.ok(css.includes('data-gps-quality="good"'));
assert.match(css,/run-measurement-post__auto-details/);
assert.match(css,/run-measurement-post__facts\.run-measurement-post__facts--secondary/);
console.log("mobileRunMeasurementExperience.test.mjs: PASS");
