import assert from 'node:assert/strict';
import { internalModules } from '../core/internal/modules.js';
import '../core/internal/modelSupport.js';
import '../core/internal/primaryModelEngine.js';
const engine=internalModules.primaryRegionalEngine;
const assertBlocked=(record,expectedUnsupported)=>{
  const out=engine.calculateRun(record);
  assert.equal(out.state,'OK');
  for(const id of engine.REGION_DEFS.map(r=>r.id)){
    const r=out.regions[id];
    assert.equal(r.value,null,`whole value must be unavailable: ${id}`);
    assert.equal(r.state,'PARTIAL_EVIDENCE',id);
    assert.ok(r.unsupportedDistanceKm>=expectedUnsupported-1e-8,`unsupported distance ${id}`);
    assert.equal(r.routeTrace.some(x=>x.speedProvenance==='MODEL_DERIVED_SEGMENT_SPEED_FALLBACK'),false,`${id} must not use old whole-run fallback`);
  }
  return out;
};
const incomplete=assertBlocked({distanceKm:5,durationMinutes:30,runningFormat:'RUN',segments:[{distanceKm:2,speedMps:2.5},{distanceKm:2,speedMps:4.5}]},1);
assert.equal(incomplete.courseState,'HYBRID_PARTIAL_SEGMENTED');
const r01=incomplete.regions.R01;
assert.equal(r01.supportedDistanceKm,4);
assert.equal(r01.unsupportedDistanceKm,1);
assert.equal(r01.routeTrace.at(-1).speedMps,null);
assert.equal(r01.routeTrace.at(-1).calculationState,'EVIDENCE_INSUFFICIENT');
assert.equal(r01.routeTrace.at(-1).speedProvenance,'MISSING_REMAINDER_SPEED');
assert.equal(r01.routeTrace.at(-1).remainderState,'UNKNOWN_REMAINDER');
assert.equal(r01.routeTrace.at(-1).sourceConditionClass,'EVIDENCE_INSUFFICIENT');
assert.ok(Number.isFinite(r01.knownValue));
const withoutSpeed=assertBlocked({distanceKm:4,durationMinutes:24,segments:[{distanceKm:2,speedMps:2.5},{distanceKm:2}]},2);
assert.equal(withoutSpeed.regions.R01.routeTrace[1].speedProvenance,'MISSING_SEGMENT_SPEED');
const explicit=engine.calculateRun({distanceKm:4,durationMinutes:24,segments:[{distanceKm:2,speedMps:2.5},{distanceKm:2,speedMps:3.5}]});
assert.equal(explicit.regions.R01.state,'OK');
assert.ok(Number.isFinite(explicit.regions.R01.value));
assert.equal(explicit.regions.R01.unsupportedDistanceKm,0);
assert.equal(explicit.regions.R11.routeTrace[0].sourceConditionClass,'SOURCE_DIRECT_RANGE');
assert.equal(explicit.regions.R11.routeTrace[0].projectDerivationMethod,'HO_MEDIAL_LATERAL_MIDFOOT_PEAK_PRESSURE_NORMALIZED_50_50');
const derived=engine.calculateRun({distanceKm:4,durationMinutes:24,segments:[{distanceKm:2,durationMinutes:800/60},{distanceKm:2,durationMinutes:600/60}]});
assert.equal(derived.regions.R01.state,'OK');
assert.equal(derived.regions.R01.routeTrace[0].speedProvenance,'SEGMENT_DISTANCE_DURATION_DERIVED');
const outside=engine.calculateRun({distanceKm:4,durationMinutes:24,segments:[{distanceKm:2,speedMps:2.5},{distanceKm:2,speedMps:1.8}]});
assert.equal(outside.regions.R01.value,null);
assert.equal(outside.regions.R01.unsupportedDistanceKm,2);
assert.equal(outside.regions.R01.state,'PARTIAL_EVIDENCE');
const tooFar=engine.calculateRun({distanceKm:4,durationMinutes:24,segments:[{distanceKm:3,speedMps:2.5},{distanceKm:2,speedMps:2.5}]});
assert.equal(tooFar.state,'SEGMENT_EXPOSURE_EXCEEDS_RUNNING_DISTANCE');
const tooLong=engine.calculateRun({distanceKm:4,durationMinutes:10,segments:[{distanceKm:2,durationMinutes:11},{distanceKm:2,speedMps:3.5}]});
assert.equal(tooLong.state,'SEGMENT_DURATION_EXCEEDS_RUNNING_DURATION');
const conflicting=engine.calculateRun({distanceKm:4,durationMinutes:24,segments:[{distanceKm:2,speedMps:4,durationMinutes:20},{distanceKm:2,speedMps:2.5}]});
assert.equal(conflicting.state,'SEGMENT_SPEED_DURATION_CONFLICT');
const noInput=engine.calculateRun({distanceKm:5,durationMinutes:30});
assert.equal(noInput.courseState,'WHOLE_RUN_ONLY');
assert.ok(Number.isFinite(noInput.regions.R01.value),'whole-run distance/time is still a valid whole-run source');
console.log('PRIMARY_MISSING_SEGMENT_EVIDENCE: 9 families / PASS');
