import { escapeHtml } from "../../ui/commonComponents.js";
import {
  compactSlopeSummary,
  compactSurfaceSummary,
  prepareCourseEditorState,
  primarySurface,
  sectionRowsCompact,
  selected,
  surfaceMixCompact,
  surfaceOptions,
} from "../shared/courseEditorScreen.js";

function renderMobileCourseEditor({preset,gpxCandidate,course,returnTo,gm,sm,manager}){
  const profileMode=gm==="SUMMARY"||gm==="SECTIONS";
  return `<div class="screen screen--course-editor screen-layout screen-layout--course course-derived-screen course-mobile-editor"><div class="editor editor--derived course-derived-frame course-derived-frame--editor"><header class="editor-head course-derived-head"><a class="editor-back-link" href="${escapeHtml(manager)}">← コース設定</a><strong>${preset?"コースを編集":"新しいコース"}</strong><span aria-hidden="true"></span></header><main class="editor-main course-derived-body"><p class="course-mobile-lead">分かる項目だけ入力します。</p>${gpxCandidate?`<div class="gpx-prefill course-mobile-gpx-prefill"><strong>ルートファイルから読み取った坂道候補を入力済み</strong><span>内容を確認して保存してください。</span></div>`:""}<form id="course-editor-form" novalidate><input type="hidden" name="courseId" value="${escapeHtml(preset?.id||"")}"><input type="hidden" name="returnTo" value="${escapeHtml(returnTo)}"><input type="hidden" name="fromGpx" value="${gpxCandidate?"1":"0"}"><input type="hidden" name="routePattern" value="${escapeHtml(course.routePattern||"UNKNOWN")}"><div class="form-messages" data-form-messages tabindex="-1" hidden></div>
  <section class="e-card course-mobile-card course-mobile-name"><div class="e-title"><b>1</b><div><small>必須</small><h2>コース名</h2></div></div><label class="field course-mobile-name-field"><span class="visually-hidden">コース名</span><input name="courseName" maxlength="80" required placeholder="例：川沿い往復" value="${escapeHtml(course.name||"")}"></label></section>
  <section class="e-card course-mobile-card course-mobile-grade"><div class="e-title"><b>2</b><div><small>分かる範囲で</small><h2>坂道</h2></div></div><select class="visually-hidden" name="gradeInputMode"><option value="UNKNOWN"${selected(gm,"UNKNOWN")}>分からない</option><option value="FLAT"${selected(gm,"FLAT")}>ほぼ平坦</option><option value="SUMMARY"${selected(gm,"SUMMARY")}>かんたん入力</option><option value="SECTIONS"${selected(gm,"SECTIONS")}>区間ごと</option></select><div class="mode course-grade-family" aria-label="坂道の状態"><button type="button" data-course-grade-family="UNKNOWN" class="${gm==="UNKNOWN"?"active":""}">不明</button><button type="button" data-course-grade-family="FLAT" class="${gm==="FLAT"?"active":""}">ほぼ平坦</button><button type="button" data-course-grade-family="PROFILE" class="${profileMode?"active":""}">坂あり</button></div><div class="course-grade-method" data-course-grade-method-panel${profileMode?"":" hidden"}><span>入力方法</span><div class="mode course-grade-method__toggle"><button type="button" data-course-grade-mode="SUMMARY" class="${gm==="SUMMARY"?"active":""}">かんたん</button><button type="button" data-course-grade-mode="SECTIONS" class="${gm==="SECTIONS"?"active":""}">区間ごと</button></div></div><div class="sub course-grade-summary" data-course-grade-summary${gm==="SUMMARY"?"":" hidden"}><div class="course-share-grid"><label class="mfield"><span>上り</span><div><input name="upPercent" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course.upPercent??0)}"><em>%</em></div></label><label class="mfield"><span>下り</span><div><input name="downPercent" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course.downPercent??0)}"><em>%</em></div></label></div><div class="easy-result"><div class="comp-head"><span>平坦</span><strong><output data-flat-share>—</output>%</strong></div></div><details class="course-grade-optional"><summary>坂の傾きも入力 <small>任意</small><i>⌄</i></summary><div class="course-grade-optional__grid"><label class="mfield"><span>上りの傾き</span><div><input name="upGradePercent" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(course.upGradePercent??"")}"><em>%</em></div></label><label class="mfield"><span>下りの傾き</span><div><input name="downGradePercent" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(course.downGradePercent??"")}"><em>%</em></div></label></div></details></div><div class="sub course-grade-sections" data-course-grade-sections${gm==="SECTIONS"?"":" hidden"}><div class="course-section-meta"><span>入力した区間の合計</span><strong><output data-section-share-total>0</output>%</strong></div><div class="section-rows">${sectionRowsCompact(course)}</div><button class="add-section" type="button" data-action="add-course-section">＋ 区間を追加</button><small class="course-section-limit">最大5区間</small></div></section>
  <section class="e-card course-mobile-card course-mobile-surface"><div class="e-title"><b>3</b><div><small>分かる範囲で</small><h2>路面</h2></div></div><select class="visually-hidden" name="surfaceInputMode"><option value="UNKNOWN"${selected(sm,"UNKNOWN")}>分からない</option><option value="SINGLE"${selected(sm,"SINGLE")}>1種類</option><option value="MIXED"${selected(sm,"MIXED")}>割合</option></select><div class="mode course-surface-mode"><button type="button" data-course-surface-mode="UNKNOWN" class="${sm==="UNKNOWN"?"active":""}">不明</button><button type="button" data-course-surface-mode="SINGLE" class="${sm==="SINGLE"?"active":""}">1種類</button><button type="button" data-course-surface-mode="MIXED" class="${sm==="MIXED"?"active":""}">割合</button></div><div class="sub course-surface-single" data-course-surface-single${sm==="SINGLE"?"":" hidden"}><label class="field"><span>主な路面</span><select name="primarySurfaceKey">${surfaceOptions(primarySurface(course))}</select></label></div><div class="sub course-surface-mixed" data-course-surface-mixed${sm==="MIXED"?"":" hidden"}><div class="comp-head"><span>路面構成</span><strong>合計 <output data-surface-share-total>0</output>%</strong></div><div class="surface-mix-grid">${surfaceMixCompact(course)}</div><p class="course-mobile-note">使った路面だけ入力。合計100%で保存します。</p></div></section>
  <section class="course-live-summary" aria-label="保存内容"><div class="course-live-summary__head"><span>保存内容</span><strong data-course-summary-name>${escapeHtml(course.name||"名称未入力")}</strong></div><div class="course-live-summary__facts"><span><small>坂道</small><b data-course-summary-grade>${escapeHtml(compactSlopeSummary(course))}</b></span><span><small>路面</small><b data-course-summary-surface>${escapeHtml(compactSurfaceSummary(course))}</b></span></div></section><div class="editor-actions course-mobile-actions"><button class="primary" type="submit">保存して使う</button></div></form></main></div></div>`;
}

export function renderCourseEditorScreen(args) {
  return renderMobileCourseEditor(prepareCourseEditorState(args));
}
