import { analyzeGpx, parseGpxText } from "../gpxLocalAnalysis.js";
import { saveGpxCandidate } from "../flowSessionState.js";
function pct(v){return Number.isFinite(Number(v))?`${Number(v).toFixed(1).replace(/\.0$/,"")}%`:"—";}
function profileSvg(points=[]){const valid=points.filter((p)=>Number.isFinite(Number(p.ele)));if(valid.length<2)return'<text x="380" y="110" text-anchor="middle">標高データが不足しています</text>';const sample=valid.filter((_,i)=>i%Math.max(1,Math.floor(valid.length/120))===0);if(sample.at(-1)!==valid.at(-1))sample.push(valid.at(-1));const vals=sample.map((p)=>Number(p.ele));const min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min);const pts=sample.map((p,i)=>`${20+i*(720/Math.max(1,sample.length-1))},${190-(Number(p.ele)-min)/span*150}`).join(" ");return`<line x1="20" y1="190" x2="740" y2="190" class="grid"></line><polyline points="${pts}" fill="none" stroke="currentColor" stroke-width="4" stroke-linejoin="round" stroke-linecap="round"></polyline><text x="20" y="25">${Math.round(max)} m</text><text x="20" y="207">${Math.round(min)} m</text>`;}
export function bindGpxAnalysis(){
  const file=document.getElementById("gpx-file"),status=document.getElementById("gpx-status"),area=document.getElementById("gpx-result-area"),apply=document.getElementById("gpx-apply"),ret=document.getElementById("gpx-return-to");if(!file||!apply)return;let candidate=null;
  const set=(id,text)=>{const el=document.getElementById(id);if(el)el.textContent=text;};
  file.addEventListener("change",async()=>{candidate=null;apply.disabled=true;area.hidden=true;const f=file.files?.[0];if(!f){status.textContent="ファイルを選択してください。";return;}try{const parsed=parseGpxText(await f.text());candidate=analyzeGpx(parsed,{fallbackName:f.name.replace(/\.gpx$/i,"")||"GPXコース"});status.textContent="端末内の解析が完了しました。";area.hidden=false;set("gpx-source-name",candidate.name||"GPX解析結果");set("gpx-source-meta",`${candidate.rawPointCount}点を端末内で解析`);set("gpx-coverage-badge",`標高 ${Math.round(Number(candidate.elevationCoverage||0)*100)}%`);set("gpx-total-distance",`${candidate.distanceKm} km`);set("gpx-elevation-coverage",`${Math.round(Number(candidate.elevationCoverage||0)*100)}%`);set("gpx-gain-loss",`${candidate.elevationGainM} / ${candidate.elevationLossM} m`);set("gpx-point-count",`${candidate.rawPointCount}点`);set("gpx-up-share",candidate.gradeKnowledge==="KNOWN_PROFILE"?pct(candidate.upPercent):"—");set("gpx-flat-share",candidate.gradeKnowledge==="KNOWN_PROFILE"?pct(candidate.flatPercent):"—");set("gpx-down-share",candidate.gradeKnowledge==="KNOWN_PROFILE"?pct(candidate.downPercent):"—");set("gpx-up-grade",candidate.gradeKnowledge==="KNOWN_PROFILE"?pct(candidate.upGradePercent):"—");set("gpx-down-grade",candidate.gradeKnowledge==="KNOWN_PROFILE"?pct(candidate.downGradePercent):"—");set("gpx-candidate-state",candidate.gradeKnowledge==="KNOWN_PROFILE"?"候補":"標高不足");set("gpx-candidate-note",candidate.gradeKnowledge==="KNOWN_PROFILE"?"上り・平坦・下りの候補です。Course Settingsで確認して保存します。":"標高カバーが不足しているため、坂道は不明のままCourse Settingsへ戻します。");const svg=document.getElementById("gpx-profile-svg");if(svg)svg.innerHTML=profileSvg(parsed.points);apply.disabled=false;}catch(error){status.textContent="GPXを解析できませんでした。ファイル内容を確認してください。";area.hidden=true;}});
  document.getElementById("gpx-reset")?.addEventListener("click",()=>{file.value="";candidate=null;apply.disabled=true;area.hidden=true;status.textContent="ファイルを選択してください。";});
  apply.addEventListener("click",()=>{if(!candidate)return;saveGpxCandidate(candidate);const returnTo=ret?.value||"#/record-input";window.location.hash=`#/course-editor?gpx=1&returnTo=${encodeURIComponent(returnTo)}`;});
}
