import { PRIMARY_REGIONAL_V2_REGION_DEFS, SURFACE_FIELDS } from "../../core/runloadCore.js";
import { consumeCourseSelection } from "../flowSessionState.js";
import { PROTOTYPE_BODY_VIEWS } from "../prototypeBodyRegionVisuals.js";

function finite(v){return v!==null&&v!==""&&Number.isFinite(Number(v));}
function courseFrom(data){try{return JSON.parse(String(data.get("courseJson")||"{}"));}catch{return {};}}
const SURFACE_CATEGORY={pavedPercent:"PAVED",trackPercent:"TRACK",treadmillPercent:"TREADMILL",soilPercent:"SOIL",trailPercent:"TRAIL",naturalGrassPercent:"NATURAL_GRASS",artificialTurfPercent:"ARTIFICIAL_TURF",sandPercent:"SAND"};
function surfaceComponents(course){return SURFACE_FIELDS.map(({recordKey})=>({userCategory:SURFACE_CATEGORY[recordKey]||recordKey,sharePercent:Number(course?.[recordKey]||0)})).filter((x)=>x.sharePercent>0);}
function engineInput(data){
  const distance=Number(data.get("distanceKm")),duration=Number(data.get("durationMinutes")),format=String(data.get("runningFormat")||"CONTINUOUS_RUN");
  if(!(distance>0&&duration>0))return {error:"距離と実走時間を確認してください。"};
  const course=courseFrom(data);const input={runningFormat:format==="RUN_WALK"?"RUN_WALK":"RUN",distanceKm:distance,durationMinutes:duration,runSetting:"OUTDOOR_ROUTE",surfaceComponents:surfaceComponents(course)};
  if(format==="RUN_WALK") {const rd=Number(data.get("runningDistanceKm")),rt=Number(data.get("runningDurationMinutes"));if(!(rd>0&&rt>0&&rd<distance&&rt<duration))return{error:"RUN_WALKでは、走った区間の距離と時間を全体より小さい値で入力してください。"};input.runningDistanceKm=rd;input.runningDurationMinutes=rt;}
  if(String(course.gradeKnowledge||"")==="KNOWN_PROFILE") {input.uphillSharePercent=Number(course.upPercent||0);input.downhillSharePercent=Number(course.downPercent||0);if(input.uphillSharePercent>0&&finite(course.upGradePercent))input.uphillGradePercent=Number(course.upGradePercent);if(input.downhillSharePercent>0&&finite(course.downGradePercent))input.downhillGradePercent=Number(course.downGradePercent);}
  if(Array.isArray(course.sections)&&course.sections.length){input.segments=course.sections.filter((s)=>Number(s.sharePercent)>0).map((s)=>({distanceKm:distance*Number(s.sharePercent)/100,gradePercent:finite(s.gradePercent)?Number(s.gradePercent):null}));}
  return {input,course};
}
function latestValues(services){const x=services.workflows.records.loadLatestExperience();return new Map((x?.regionalV2Result?.regions||[]).map((r)=>[r.regionId,r.value]));}
function referenceState(value){if(!finite(value))return"unavailable";const d=Number(value)-100;return Math.abs(d)<1?"reference":d>0?"above":"below";}
function compareState(value,previous){if(!finite(value)||!finite(previous))return"unavailable";const d=Number(value)-Number(previous);return Math.abs(d)<1?"reference":d>0?"above":"below";}
function signed(v){if(!finite(v))return"—";const n=Number(v);return`${n>0?"+":""}${n.toFixed(1)}`;}
function pace(distance,duration){const d=Number(distance),t=Number(duration);if(!(d>0&&t>0))return"—";const s=Math.round(t*60/d);return`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")} /km`;}
function resultRows(result){return PRIMARY_REGIONAL_V2_REGION_DEFS.map((def)=>({def,row:result?.regions?.[def.id]||null,value:result?.regions?.[def.id]?.value}));}
function bodyMap(rows,previous,compare){const byId=new Map(rows.map((item)=>[item.def.displayId,item]));return PROTOTYPE_BODY_VIEWS.map((view)=>`<figure class="body-view"><figcaption>${view.title}</figcaption><svg viewBox="70 10 160 430" aria-label="${view.title}の部位図"><defs><pattern id="sim-hatch-${view.key}" width="10" height="10" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="10" height="10" fill="currentColor" opacity=".08"></rect><line x1="0" y1="0" x2="0" y2="10" stroke="currentColor" stroke-width="3" opacity=".24"></line></pattern></defs><g class="body-silhouette">${view.silhouette}</g>${view.paths.map(([id,d])=>{const item=byId.get(id),value=item?.value,prev=previous.get(id);const state=compare?compareState(value,prev):referenceState(value);return`<path class="region-path" data-direction="${state}" data-region-id="${id}"${state==="unavailable"?` style="fill:url(#sim-hatch-${view.key})"`:""} d="${d}"><title>${item?.def?.name||id}：${finite(value)?Number(value).toFixed(1):"数値なし"}</title></path>`;}).join("")}</svg></figure>`).join("");}
function render(result,previous,compare,distance,course){
  const rows=resultRows(result); const list=rows.map(({def,value})=>{const prev=previous.get(def.displayId);const delta=finite(value)&&finite(prev)?Number(value)-Number(prev):null;const state=compare?compareState(value,prev):referenceState(value);return`<div class="region-row" data-direction="${state}"><span class="region-copy"><strong>${def.name}</strong><small>${compare?(finite(prev)?`前回 ${Number(prev).toFixed(1)}`:"前回比較なし"):"その部位自身の基準100"}</small></span><span class="region-metric"><strong>${finite(value)?Number(value).toFixed(1):"—"}</strong><small>${compare?(finite(delta)?`前回差 ${signed(delta)}`:"比較なし"):`基準100から ${finite(value)?signed(Number(value)-100):"—"}`}</small></span></div>`;}).join("");
  const legend=compare?'<li><i class="above"></i>前回より上</li><li><i class="reference"></i>ほぼ同じ</li><li><i class="below"></i>前回より下</li><li><i class="unavailable"></i>比較なし</li>':'<li><i class="above"></i>基準100より上</li><li><i class="reference"></i>基準100付近</li><li><i class="below"></i>基準100より下</li><li><i class="unavailable"></i>表示なし</li>';
  return `<div class="result-layout"><div><ul class="direction-legend" aria-label="身体図の色">${legend}</ul><div class="body-map">${bodyMap(rows,previous,compare)}</div><p class="map-note">${compare?"同じ部位について前回の保存記録との差を色で示します。上・下は良し悪しを示しません。":"各部位自身の基準100に対する方向を示します。別部位どうしを比べません。"}</p></div><aside class="region-panel"><div class="region-panel-head"><div><small>12 REGIONS</small><strong>${compare?"12部位の前回差":"12部位のReference-100"}</strong></div><button type="button" data-action="simulation-toggle-compare" aria-pressed="${compare}">${compare?"Reference-100を見る":"前回差を見る"}</button></div><div class="region-list">${list}</div></aside></div><p class="compact-boundary">距離 ${Number(distance).toFixed(1)} km は別の走行事実です。部位値へ自動乗算しません。計算状態：${result?.state||"—"}</p>`;
}
export function bindSimulation({services}){
  const form=document.getElementById("simulation-form"),target=document.getElementById("simulation-result");if(!form||!target)return;let compare=true;const previous=latestValues(services);
  function update(){const data=new FormData(form);const runWalk=String(data.get("runningFormat"))==="RUN_WALK";form.querySelector('[data-simulation-run-walk]').hidden=!runWalk;const built=engineInput(data);const warning=form.querySelector('[data-simulation-input-warning]');if(built.error){target.innerHTML="";if(warning){warning.hidden=false;warning.textContent=built.error;}return;}if(warning)warning.hidden=true;const result=services.model.primaryRegionalV2.calculatePrimaryRegionalV2(built.input);const d=Number(data.get("distanceKm")),t=Number(data.get("durationMinutes"));const p=pace(d,t);const set=(sel,text)=>{const el=form.querySelector(sel);if(el)el.textContent=text;};set('[data-simulation-derived-pace]',p);set('[data-simulation-current-summary]',`${d.toFixed(1)} km・${Math.round(t)}分`);set('[data-simulation-current-pace]',`${p}・${built.course.name||"コース未選択"}`);const calc=form.querySelector('.calc-state');if(calc)calc.textContent=result?.state==="OK"?"計算済み":"確認が必要";target.innerHTML=render(result,previous,compare,d,built.course);bindToggle();}
  function bindToggle(){target.querySelector('[data-action="simulation-toggle-compare"]')?.addEventListener("click",()=>{compare=!compare;update();});}
  form.addEventListener("input",update);form.addEventListener("change",update);form.addEventListener("reset",()=>setTimeout(update,0));consumeCourseSelection("simulation");update();
}
