import "./planWorkflow.js";
import { internalModules } from "./modules.js";

// ===== data/evidenceGovernanceData.js =====
{
const moduleExports = Object.create(null);
const EVIDENCE_GOVERNANCE_VERSION = "evidence-governed-columns-v6";
const EVIDENCE_GOVERNANCE_REVIEW_DATE = "2026-10-06";

function freezeList(items = []) {
  return Object.freeze([...items]);
}

function sourceRecord(input) {
  return Object.freeze({
    ...input,
    modelSourceIds: freezeList(input.modelSourceIds),
    anchorIds: freezeList(input.anchorIds),
    relatedInputs: freezeList(input.relatedInputs),
    relatedRoutes: freezeList(input.relatedRoutes),
    relatedRegions: freezeList(input.relatedRegions),
  });
}

function articleRecord(input) {
  return Object.freeze({
    ...input,
    sourceIds: freezeList(input.sourceIds),
    relatedInputs: freezeList(input.relatedInputs),
    relatedRoutes: freezeList(input.relatedRoutes),
    relatedRegions: freezeList(input.relatedRegions),
  });
}

const SOURCE_EVIDENCE_REGISTRY = Object.freeze([
  sourceRecord({
    sourceId: "APP-SPEC-CURRENT",
    sourceRole: "CURRENT_INTERNAL_SPECIFICATION",
    title: "Application model, output, and claim-boundary specifications",
    locator: "Master V1.10: 02_INPUT_OUTPUT_UI_CURRENT/03_OUTPUT_UI_SEMANTIC_CONTRACT_CURRENT.md; 03_REGIONAL_A4_MODEL_CURRENT/00, 12, 13, 24",
    evidenceStatus: "CURRENT_INTERNAL_SPEC",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: ["記事ごとの関連入力", "表示状態", "比較signature"],
    relatedRoutes: ["表示契約", "情報分離", "非主張境界"],
    relatedRegions: ["記事ごとの対象部位"],
    allowedClaim: "Current仕様で固定した計算の意味、表示状態、情報分離、非主張境界を説明できる。",
    prohibitedClaim: "臨床妥当性、個人の安全、傷害確率、診断、走行可否を証明する資料として扱わない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-MINETTI",
    sourceRole: "APP_READING_BACKGROUND",
    title: "Energy cost of walking and running at extreme uphill and downhill slopes",
    locator: "Methods/equation and grade-cost results / PDF pp.3-6; Current packaged PDF identity in Source Crosswalk",
    evidenceStatus: "FULL_TEXT_IDENTITY_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["SRC-NEW-001"],
    anchorIds: [],
    relatedInputs: ["代表勾配", "上り区間割合", "下り区間割合"],
    relatedRoutes: ["general-knowledge grade energy-cost reading"],
    relatedRegions: ["なし（総合推定負荷の別指標）"],
    allowedClaim: "資料内の勾配と代謝コストの方向・比率を、資料条件の範囲で説明できる。",
    prohibitedClaim: "個人の消費エネルギー実測値、疲労、傷害、走行可否へ変換しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-VAN-HOOREN",
    sourceRole: "PRIMARY_REGIONAL_AND_APP_READING",
    title: "Per-step and cumulative load at three common running injury locations: The effect of speed, surface gradient, and cadence",
    locator: "Table 2 / PDF p.9",
    evidenceStatus: "FULL_TEXT_AND_A4_ANCHORS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["BAT-SRC-010"],
    anchorIds: ["RCM-ANCH-001..039"],
    relatedInputs: ["速度", "勾配", "cadence"],
    relatedRoutes: ["Regional A4 SPEED", "Regional A4 GRADE", "Regional A4 CADENCE"],
    relatedRegions: ["膝蓋大腿関節領域", "アキレス腱領域", "足底腱膜領域"],
    allowedClaim: "資料の条件・endpoint・範囲内で、3領域の累積代理指標の方向と比率を説明できる。",
    prohibitedClaim: "3領域以外へ一般化せず、傷害確率、危険順位、共通物理単位、因果関係を主張しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-NUCKOLS",
    sourceRole: "PRIMARY_REGIONAL_AND_APP_READING",
    title: "Mechanics of walking and running up and downhill: a joint-level perspective",
    locator: "Table 1 / PDF p.6",
    evidenceStatus: "FULL_TEXT_AND_A4_ANCHORS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["SRC-SUP-003"],
    anchorIds: ["RCM-ANCH-A3-001..015"],
    relatedInputs: ["勾配"],
    relatedRoutes: ["Regional A4 GRADE_JOINT_POWER"],
    relatedRegions: ["股関節領域", "大腿前面領域", "足関節領域"],
    allowedClaim: "資料のjoint-power条件と指定proxy変換の範囲で、勾配による方向差を説明できる。",
    prohibitedClaim: "筋・腱・関節の実測負荷や、全12部位の直接測定として扱わない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-VOLOSHINA",
    sourceRole: "REGIONAL_A4_AND_APP_READING",
    title: "Biomechanics and energetics of running on uneven terrain",
    locator: "Results / PDF pp.3-6",
    evidenceStatus: "FULL_TEXT_IDENTITY_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["BAT-SRC-027"],
    anchorIds: [],
    relatedInputs: ["路面の凹凸"],
    relatedRoutes: ["Regional A4 uneven-surface context"],
    relatedRegions: ["下肢全体"],
    allowedClaim: "研究条件の範囲で、凹凸のある路面では平らな路面と身体の安定化やエネルギー面の反応が異なることを一般的に説明できる。",
    prohibitedClaim: "個人の障害原因、転倒確率、走行可否、あらゆる自然路面への一般化には用いない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-HORIGUCHI",
    sourceRole: "REGIONAL_A4_AND_APP_READING",
    title: "Effects of uphill and downhill running on plantar pressure distribution in different foot strike patterns",
    locator: "Table 1 / PDF p.3; Methods / pp.2-3; limitations / pp.7-8",
    evidenceStatus: "FULL_TEXT_AND_A4_ANCHORS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["SRC-A4-001"],
    anchorIds: ["RCM-ANCH-A4-001..011"],
    relatedInputs: ["勾配", "足部接地"],
    relatedRoutes: ["Regional A4 grade and foot-strike context"],
    relatedRegions: ["後足部", "足底中部", "前足部"],
    allowedClaim: "研究条件の範囲で、上り・下りと足部接地の違いにより足底圧分布が異なることを一般的に説明できる。",
    prohibitedClaim: "個人の接地型を推定せず、障害原因、最適な接地、走行可否には用いない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-LINTON",
    sourceRole: "RESEARCH_PLAN_AND_APP_READING",
    title: "Running-Centred Injury Prevention Support: A Scoping Review on Current Injury Risk Reduction Practices for Runners",
    locator: "Review scope, support practices, and limitations / PDF pp.1, 25; Current finding CUR-FND-021",
    evidenceStatus: "FULL_TEXT_AND_CURRENT_FINDINGS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-015"],
    anchorIds: [],
    relatedInputs: ["本人申告", "相談用共有範囲", "記録文脈"],
    relatedRoutes: ["deterministic consultation information-organization route"],
    relatedRegions: ["本人が選択した部位のみ"],
    allowedClaim: "ランナー支援で記録・教育・専門家への共有が検討される背景を一般的に説明できる。",
    prohibitedClaim: "このアプリの傷害予防効果、診断精度、相談結果の有効性を主張しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-BUIST",
    sourceRole: "RESEARCH_PLAN_AND_APP_READING",
    title: "No Effect of a Graded Training Program on the Number of Running-Related Injuries in Novice Runners: A Randomized Controlled Trial",
    locator: "Trial program, results, and limitations / PDF pp.3, 9; Current findings CUR-FND-006..007",
    evidenceStatus: "FULL_TEXT_AND_CURRENT_FINDINGS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-005"],
    anchorIds: [],
    relatedInputs: ["予定距離", "予定時間", "予定と実績"],
    relatedRoutes: ["general-knowledge column route", "plan non-prescription boundary"],
    relatedRegions: ["なし（走行全体の練習計画）"],
    allowedClaim: "初心者を対象に10％ルールを用いた13週間の段階的プログラムが、標準プログラムよりランニング関連傷害を減らさなかったことを研究条件付きで説明できる。",
    prohibitedClaim: "安全な増加率、急増の許容、個人の傷害予防、最適な練習計画を導かない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-KRUKOWSKI",
    sourceRole: "RESEARCH_PLAN_AND_APP_READING",
    title: "Impact of feedback generation and presentation on self-monitoring behaviors, dietary intake, physical activity, and weight: a systematic review and meta-analysis",
    locator: "Physical-activity findings and review limitations / PDF pp.1, 16; Current finding CUR-FND-013",
    evidenceStatus: "FULL_TEXT_AND_CURRENT_FINDINGS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-008"],
    anchorIds: [],
    relatedInputs: ["記録目的", "本人メモ", "フィードバック表示"],
    relatedRoutes: ["general-knowledge column route", "non-evaluative feedback boundary"],
    relatedRegions: ["なし（行動・記録文脈）"],
    allowedClaim: "身体活動介入ではフィードバックに小さな優位がみられた一方、最適な生成・提示方法の証拠は一定しなかったことを説明できる。",
    prohibitedClaim: "このアプリによる行動変容の効果、継続効果、初心者ランナーへの個別効果を主張しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-KARAHANOGLU",
    sourceRole: "RESEARCH_PLAN_AND_APP_READING",
    title: "How Are Sports-Trackers Used by Runners? Running-Related Data, Personal Goals, and Self-Tracking in Running",
    locator: "Goals, tracker uses, and design implications / PDF pp.1, 12; Current findings CUR-FND-016..017",
    evidenceStatus: "FULL_TEXT_AND_CURRENT_FINDINGS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-011"],
    anchorIds: [],
    relatedInputs: ["記録目的", "履歴", "本人メモ"],
    relatedRoutes: ["general-knowledge column route", "running-goal reading route"],
    relatedRegions: ["なし（ランナーの記録利用）"],
    allowedClaim: "調査対象者が記録保存と振り返り・行動の両方にデータを使い、状況に応じて目標を変えていたことを説明できる。",
    prohibitedClaim: "経験豊富な機器利用者の結果を初心者全員へ一般化せず、特定の記録方法の優位性を主張しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-JANSSEN",
    sourceRole: "RESEARCH_PLAN_AND_APP_READING",
    title: "Understanding Different Types of Recreational Runners and How They Use Running-Related Technology",
    locator: "Runner profiles and technology-use differences / PDF pp.1, 14; Current finding CUR-FND-018",
    evidenceStatus: "FULL_TEXT_AND_CURRENT_FINDINGS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-012"],
    anchorIds: [],
    relatedInputs: ["記録目的", "技術利用", "本人の関心"],
    relatedRoutes: ["general-knowledge column route", "running-goal reading route"],
    relatedRegions: ["なし（ランナーの多様性）"],
    allowedClaim: "レクリエーショナルランナーの態度・関心・技術利用が一様でなかったことを説明できる。",
    prohibitedClaim: "4類型をアプリ利用者の分類や自動判定へ使わず、初心者固有の結果としない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-WINTER",
    sourceRole: "RESEARCH_PLAN_AND_APP_READING",
    title: "A Multifactorial Approach to Overuse Running Injuries: A 1-Year Prospective Study",
    locator: "Studied factors and predictor limitations / PDF pp.1, 7; Current finding CUR-FND-022",
    evidenceStatus: "FULL_TEXT_AND_CURRENT_FINDINGS_VERIFIED_WITH_METHOD_LIMITATION",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-016"],
    anchorIds: [],
    relatedInputs: ["生活背景メモ", "練習記録", "過去の経験"],
    relatedRoutes: ["general-knowledge column route", "context-only information route"],
    relatedRegions: ["なし（複数背景要因の説明）"],
    allowedClaim: "複数の練習・身体・既往・バイオメカニクス要因が検討され、研究自体も頑健な個人予測を支持しなかったことを説明できる。",
    prohibitedClaim: "観察された関連を個人の因果関係、傷害予測、アプリ独自の係数へ変換しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-BESOMI",
    sourceRole: "RESEARCH_PLAN_AND_APP_READING",
    title: "Exploring contextual factors for management and prevention of running-related injuries: runners and experts’ perspectives",
    locator: "Experience, context, and information-reliability findings / PDF pp.1, 3, 9; Current finding CUR-FND-027",
    evidenceStatus: "FULL_TEXT_AND_CURRENT_FINDINGS_VERIFIED_WITH_CONTEXT_LIMITATION",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-021"],
    anchorIds: [],
    relatedInputs: ["生活背景メモ", "本人の経験", "相談用メモ"],
    relatedRoutes: ["general-knowledge column route", "consultation information-organization route"],
    relatedRegions: ["なし（本人と専門家の見方）"],
    allowedClaim: "経験や文脈が認識・行動に関係し、経験の少ないランナーが情報の信頼性判断に迷う場合があったことを説明できる。",
    prohibitedClaim: "限定された傷害関連の質的研究から、全初心者の問題、因果関係、このアプリの有効性を証明しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-COOLDOWN-VAN-HOOREN",
    sourceRole: "APP_READING_CONTENT",
    title: "Do We Need a Cool-Down After Exercise? A Narrative Review of the Psychophysiological Effects and the Effects on Performance, Injuries and the Long-Term Adaptive Response",
    locator: "Abstract, evidence summary, and conclusions / PDF pp.1, 16; Current source CUR-SRC-022",
    evidenceStatus: "FULL_TEXT_IDENTITY_VERIFIED_CC_BY_4_0",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-022"],
    anchorIds: [],
    relatedInputs: ["運動後に行ったこと", "本人の感じ方", "本人メモ"],
    relatedRoutes: ["general-knowledge column route", "non-prescriptive after-run reading route"],
    relatedRegions: ["なし（運動後の一般的な振り返り）"],
    allowedClaim: "能動的クールダウンの回復指標に対する結果が限定的または一定せず、けが予防が確認された方法ではないことを研究範囲付きで説明できる。",
    prohibitedClaim: "個人向けの方法・強さ・時間、治療効果、けが予防、回復保証、走行可否を導かない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-AFONSO",
    sourceRole: "APP_READING_CONTENT",
    title: "The Effectiveness of Post-exercise Stretching in Short-Term and Delayed Recovery of Strength, Range of Motion and Delayed Onset Muscle Soreness: A Systematic Review and Meta-Analysis of Randomized Controlled Trials",
    locator: "Abstract, GRADE assessment, limitations, and conclusions / PDF pp.1, 22-23; Current source CUR-SRC-023",
    evidenceStatus: "FULL_TEXT_IDENTITY_VERIFIED_CC_BY_4_0_WITH_VERY_LOW_CERTAINTY",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-023"],
    anchorIds: [],
    relatedInputs: ["運動後のストレッチ記録", "筋肉痛の本人メモ", "本人の感じ方"],
    relatedRoutes: ["general-knowledge column route", "evidence-certainty boundary"],
    relatedRegions: ["なし（運動後の一般的な回復指標）"],
    allowedClaim: "運動後ストレッチは受動的休養と比べ、筋肉痛や筋力回復の明確な改善が確認されず、証拠の確かさがとても低かったことを説明できる。",
    prohibitedClaim: "ストレッチを一律に勧めたり禁止したりせず、個人の治療、予防、回復、走行可否へ一般化しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-HEW-BUTLER",
    sourceRole: "APP_READING_CONTENT",
    title: "Exercise-Associated Hyponatremia: 2017 Update",
    locator: "Abstract, etiology, and prevention discussion / PDF pp.1, 3-4, 8; Current source CUR-SRC-024",
    evidenceStatus: "FULL_TEXT_IDENTITY_VERIFIED_CC_BY_4_0",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-024"],
    anchorIds: [],
    relatedInputs: ["走行時間", "天候メモ", "食事・水分の自己記録"],
    relatedRoutes: ["general-knowledge column route", "non-diagnostic hydration reading route"],
    relatedRegions: ["なし（水分摂取の一般的な背景）"],
    allowedClaim: "主に持久性運動の文献で、のどの渇きを超える飲み過ぎが運動関連低ナトリウム血症の主要背景と整理されていることを説明できる。",
    prohibitedClaim: "個人の必要量、脱水・低ナトリウム血症、電解質、治療、走行可否を判定または処方しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-ARENT",
    sourceRole: "APP_READING_CONTENT",
    title: "Nutrient Timing: A Garage Door of Opportunity?",
    locator: "Abstract, post-exercise context, practical application, and conclusion / PDF pp.1, 8-10, 17; Current source CUR-SRC-025",
    evidenceStatus: "FULL_TEXT_IDENTITY_VERIFIED_CC_BY_4_0",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-025"],
    anchorIds: [],
    relatedInputs: ["運動内容", "次の運動までの間隔", "食事・水分の自己記録"],
    relatedRoutes: ["general-knowledge column route", "non-prescriptive nutrition reading route"],
    relatedRegions: ["なし（運動後の食事文脈）"],
    allowedClaim: "栄養を取る時機の重要性が運動内容・頻度・次の運動までの間隔などに依存し、一日の摂取全体と切り離せないことを説明できる。",
    prohibitedClaim: "個人の摂取量・食品・補助食品・時刻、栄養状態、回復効果、走行可否を評価または処方しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-DOHERTY-SLEEP",
    sourceRole: "APP_READING_CONTENT",
    title: "The Sleep and Recovery Practices of Athletes",
    locator: "Abstract, sleep domains, self-report limits, and discussion / PDF pp.1, 16-19; Current source CUR-SRC-026",
    evidenceStatus: "FULL_TEXT_IDENTITY_VERIFIED_CC_BY_4_0",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-026"],
    anchorIds: [],
    relatedInputs: ["睡眠の本人メモ", "睡眠時間", "本人の感じ方"],
    relatedRoutes: ["general-knowledge column route", "non-diagnostic sleep reading route"],
    relatedRegions: ["なし（睡眠と回復の一般的な背景）"],
    allowedClaim: "競技者の睡眠には個人差があり、時間だけでなく質・量・時機を分け、自己記録の限界も含めて考える必要があることを説明できる。",
    prohibitedClaim: "競技者338人の横断的な自己記録から、初心者個人の必要時間、睡眠障害、回復状態、原因、走行可否を判定または処方しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-GRUNDSTEIN-HEAT",
    sourceRole: "APP_READING_CONTENT",
    title: "Influence of Race Performance and Environmental Conditions on Exertional Heat Stroke Prevalence Among Runners Participating in a Warm Weather Road Race",
    locator: "Abstract, methods, discussion, and limitations / PDF pp.1-5; Current source CUR-SRC-027",
    evidenceStatus: "FULL_TEXT_IDENTITY_VERIFIED_CC_BY_4_0",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-027"],
    anchorIds: [],
    relatedInputs: ["気温", "天候メモ", "時間帯", "走行ペース"],
    relatedRoutes: ["general-knowledge column route", "non-diagnostic heat-context reading route"],
    relatedRegions: ["なし（暑熱環境と走行全体の背景）"],
    allowedClaim: "特定の温暖な11.26kmレースの後ろ向き研究で、WBGTと平均ペースを含む複数条件が検討され、関連のみが示されたことを範囲付きで説明できる。",
    prohibitedClaim: "一つの大会の関連から、個人の原因、熱中症、危険度、安全なペース、水分量、運動可否を推定または処方しない。",
  }),
  sourceRecord({
    sourceId: "APP-GUIDE-JSPO-HEAT",
    sourceRole: "PUBLIC_GUIDANCE_FOR_APP_READING",
    title: "スポーツ活動中の熱中症予防ガイドブック",
    locator: "日本スポーツ協会の現行公開ページとガイドブック案内（2026-08-06確認、2025年6月第6版改訂）",
    evidenceStatus: "OFFICIAL_CURRENT_PUBLIC_GUIDANCE_PAGE_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: ["気温", "天候メモ", "走る場所と時間"],
    relatedRoutes: ["public heat guidance link", "external current-information check boundary"],
    relatedRegions: ["なし（スポーツ活動時の暑熱環境）"],
    allowedClaim: "スポーツ活動時の暑さを考える公的指標としてWBGTを紹介し、場所と時間に合う最新の公式情報をアプリ外で確認する必要を説明できる。",
    prohibitedClaim: "公開資料をアプリ内の自動判定へ置き換えず、固定した閾値、個人の安全、診断、運動の中止・実施可否を決めない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-KWON-TALK",
    sourceRole: "APP_READING_CONTENT",
    title: "The talk test as a useful tool to monitor aerobic exercise intensity in healthy population",
    locator: "Abstract, participants, protocol, discussion, and limitations / PDF pp.1-7; Current source CUR-SRC-028",
    evidenceStatus: "FULL_TEXT_IDENTITY_VERIFIED_CC_BY_NC_4_0",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: ["CUR-SRC-028"],
    anchorIds: [],
    relatedInputs: ["走行ペース", "会話のしやすさの本人メモ"],
    relatedRoutes: ["general-knowledge column route", "subjective talk-ease reading route"],
    relatedRegions: ["なし（走行全体の主観的な強さ）"],
    allowedClaim: "健康成人17人のトレッドミル研究で、3段階の会話テストと複数の生理・心理指標に関連があったことを、標本と条件の限界付きで説明できる。",
    prohibitedClaim: "小規模な実験室研究から、初心者全員の正確なペース、心肺機能、病気、安全な強さ、走行可否を評価または処方しない。",
  }),

  sourceRecord({
    sourceId: "APP-COL-PLOS-SURFACE-2025",
    sourceRole: "APP_READING_CONTENT",
    title: "Influences of footstrike patterns and overground conditions on lower extremity kinematics and kinetics during running",
    locator: "Open Access full text / PLOS ONE 2025",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "路面条件とfoot strikeによる下肢kinematics/kineticsの違いを研究条件の範囲で説明できる。",
    prohibitedClaim: "最適路面、個人の障害原因、傷害予防効果へ一般化しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-ROF-2017",
    sourceRole: "APP_READING_CONTENT",
    title: "Development and Validity of the Rating-of-Fatigue Scale",
    locator: "Open Access full text / Sports Medicine 2017",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "0〜10のRating-of-Fatigue Scaleが主観的疲労の評価尺度として開発・検証された背景を説明できる。",
    prohibitedClaim: "診断、運動可否、他人との直接比較へ変換しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-ROF-J-2026",
    sourceRole: "APP_READING_CONTENT",
    title: "Validation of the Japanese Version of the Rating of Fatigue Scale",
    locator: "Open Access full text / Sports Medicine - Open 2026",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "日本語版ROF尺度の検証と正式な日本語表現を説明できる。",
    prohibitedClaim: "ライセンス条件を超えた改変や診断用途に用いない。",
  }),
  sourceRecord({
    sourceId: "APP-GUIDE-MHLW-SAFE-2023",
    sourceRole: "PUBLIC_GUIDANCE_FOR_APP_READING",
    title: "健康づくりのための身体活動・運動ガイド2023：身体活動・運動を安全に行うためのポイント",
    locator: "厚生労働省 現行公開ページ / 2026-10-06確認",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "運動前・中・後の体調確認、ウォームアップ、クールダウン、運動中止サインを公的案内の範囲で説明できる。",
    prohibitedClaim: "個人の診断、走行許可、治療方針に変換しない。",
  }),
  sourceRecord({
    sourceId: "APP-GUIDE-MHLW-HEAT",
    sourceRole: "PUBLIC_GUIDANCE_FOR_APP_READING",
    title: "熱中症が疑われる人を見かけたら",
    locator: "厚生労働省 現行公開ページ / 2026-10-06確認",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "熱中症が疑われ、自力飲水不可・意識なし等の場面で救急対応を優先する公的案内を説明できる。",
    prohibitedClaim: "アプリ独自の熱中症診断・救急判定へ拡張しない。",
  }),
  sourceRecord({
    sourceId: "APP-GUIDE-MHLW-STRENGTH-2023",
    sourceRole: "PUBLIC_GUIDANCE_FOR_APP_READING",
    title: "健康づくりのための身体活動・運動ガイド2023：筋力トレーニングについて",
    locator: "厚生労働省 現行公開ページ / 2026-10-06確認",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "筋力トレーニングを一般的身体活動の一部として紹介できる。",
    prohibitedClaim: "ランナー個人への筋トレ処方や傷害予防効果に変換しない。",
  }),
  sourceRecord({
    sourceId: "APP-GUIDE-NHS-C25K",
    sourceRole: "PUBLIC_GUIDANCE_FOR_APP_READING",
    title: "Couch to 5K running plan",
    locator: "NHS current public page / 2026-10-06確認",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "run/walk、休養日、段階的な初心者プログラムの実例を紹介できる。",
    prohibitedClaim: "9週間・週3回・各時間を全員への処方や安全基準にしない。",
  }),
  sourceRecord({
    sourceId: "APP-GUIDE-NHS-RUNNING-INJURIES",
    sourceRole: "PUBLIC_GUIDANCE_FOR_APP_READING",
    title: "Knee pain and other running injuries",
    locator: "NHS current public page / 2026-10-06確認",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "強い痛み、腫れ、改善しない痛み等で医療相談を考える一般情報を紹介できる。",
    prohibitedClaim: "症状から障害名・原因を診断しない。",
  }),
  sourceRecord({
    sourceId: "APP-GUIDE-ODPHP-PAG2",
    sourceRole: "PUBLIC_GUIDANCE_FOR_APP_READING",
    title: "Physical Activity Guidelines for Americans, 2nd edition",
    locator: "Official public PDF / 2026-10-06確認",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "活動量を少ない量から徐々に増やす一般的原則を説明できる。",
    prohibitedClaim: "初心者ランニングの固定スケジュールや安全な増加率に変換しない。",
  }),
  sourceRecord({
    sourceId: "APP-COL-STRENGTH-RUNNING-2024",
    sourceRole: "APP_READING_CONTENT",
    title: "Effect of Strength Training Programs in Middle- and Long-Distance Runners’ Economy at Different Running Speeds",
    locator: "Open Access systematic review / Sports Medicine 2024",
    evidenceStatus: "PUBLIC_OR_OPEN_ACCESS_VERIFIED",
    reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
    modelSourceIds: [],
    anchorIds: [],
    relatedInputs: [],
    relatedRoutes: ["general-knowledge reading route"],
    relatedRegions: ["なし（一般知識）"],
    allowedClaim: "筋力トレーニングとrunning economyの関係が研究されていることを対象集団の範囲付きで説明できる。",
    prohibitedClaim: "初心者への処方や傷害予防効果へ一般化しない。",
  }),
]);

const SOURCE_BY_ID = new Map(SOURCE_EVIDENCE_REGISTRY.map((source) => [source.sourceId, source]));

const ARTICLE_EVIDENCE_REGISTRY = Object.freeze([
  articleRecord({
    articleId: "regional-three-views", claimId: "COL-CLM-002", sourceIds: ["APP-SPEC-CURRENT", "APP-COL-VAN-HOOREN", "APP-COL-NUCKOLS"],
    relatedInputs: ["速度", "勾配", "cadence", "路面", "足部接地ほかA4 route入力"], relatedRoutes: ["Regional A4 endpoint-family routes", "coverage/status route"], relatedRegions: ["12部位"],
    allowedClaim: "各部位固有Reference 100、endpoint、算出状態、反映理由の読み方を説明する。",
    prohibitedClaim: "部位間順位、共通物理単位、傷害確率、危険度として読ませない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "regional-six-eight-28", claimId: "COL-CLM-003", sourceIds: ["APP-SPEC-CURRENT"],
    relatedInputs: ["詳細身体記録", "左右", "程度", "気づいた時点"], relatedRoutes: ["self-report route", "Regional A4 separate display route"], relatedRegions: ["本人入力28領域", "Regional A4 12部位"],
    allowedClaim: "本人申告と走行条件モデルが異なる情報層であることを説明する。",
    prohibitedClaim: "一致・不一致から原因、診断、走行起因性を推定しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "grade-and-coverage", claimId: "COL-CLM-005", sourceIds: ["APP-SPEC-CURRENT", "APP-COL-MINETTI", "APP-COL-VAN-HOOREN", "APP-COL-NUCKOLS"],
    relatedInputs: ["上り割合", "下り割合", "代表勾配", "勾配把握状態"], relatedRoutes: ["Regional A4 grade routes", "supported-domain route"], relatedRegions: ["routeごとの対応部位"],
    allowedClaim: "区間割合、代表勾配、資料範囲、反映率を分けて扱う設計を説明する。",
    prohibitedClaim: "範囲外を端値へ丸めず、コース全変化や実測組織負荷として扱わない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "surface-missingness", claimId: "COL-CLM-006", sourceIds: ["APP-SPEC-CURRENT", "APP-COL-VOLOSHINA", "APP-COL-HORIGUCHI", "APP-COL-PLOS-SURFACE-2025"],
    relatedInputs: ["路面性質", "路面の凹凸", "勾配", "足部接地"], relatedRoutes: ["surface and foot-strike explanatory route", "unknown route"], relatedRegions: ["足底部と下肢"],
    allowedClaim: "路面の硬さや凹凸、坂、足部接地により足底圧や身体の反応が異なるという研究知見を一般的に説明する。",
    prohibitedClaim: "路面名だけで個人の反応を決めず、障害原因や最適条件、走行可否を示さない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "personal-reference", claimId: "COL-CLM-007", sourceIds: ["APP-SPEC-CURRENT"],
    relatedInputs: ["比較signature", "過去の同一部位結果", "coverage", "model version"], relatedRoutes: ["directly comparable history route"], relatedRegions: ["本人が選択した同一部位"],
    allowedClaim: "適格な過去記録だけを用いる本人内比較の表示条件を説明する。",
    prohibitedClaim: "正常値、適応、危険な変化、因果関係として扱わない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "history-compatible", claimId: "COL-CLM-008", sourceIds: ["APP-SPEC-CURRENT"],
    relatedInputs: ["活動種別", "model version", "result state", "比較基準"], relatedRoutes: ["history compatibility route"], relatedRegions: ["選択した同一部位"],
    allowedClaim: "同一モデル版・同一比較条件だけを系列化し、空白や休養を0へ補完しないルールを説明する。",
    prohibitedClaim: "異なるモデル・部位・比較基準を同じ系列として比較しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "plan-facts-current", claimId: "COL-CLM-009", sourceIds: ["APP-SPEC-CURRENT"],
    relatedInputs: ["予定距離", "予定コース条件"], relatedRoutes: ["plan preview route separated from completed records"], relatedRegions: ["予定表示で選択した部位"],
    allowedClaim: "予定の入力事実が完了記録とは別に保存され、後から条件差を見返せることを説明する。",
    prohibitedClaim: "結果予測、練習処方、実施の推奨、安全保証として扱わない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "consultation-prep", claimId: "COL-CLM-010", sourceIds: ["APP-SPEC-CURRENT", "APP-COL-LINTON"],
    relatedInputs: ["本人申告", "走行事実", "選択部位", "共有範囲"], relatedRoutes: ["deterministic consultation route"], relatedRegions: ["本人が明示選択した1部位"],
    allowedClaim: "本人入力、走行事実、モデル表示を分け、共有前に整理する方法を説明する。",
    prohibitedClaim: "診断、原因特定、走行可否、治療・練習処方を行わない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "slope-endpoints", claimId: "COL-CLM-011", sourceIds: ["APP-SPEC-CURRENT", "APP-COL-VAN-HOOREN", "APP-COL-NUCKOLS"],
    relatedInputs: ["勾配", "速度", "cadence", "選択部位"], relatedRoutes: ["Regional A4 grade/speed/cadence endpoint routes"], relatedRegions: ["routeとendpointが対応する部位"],
    allowedClaim: "部位ごとに異なるendpointと資料条件を使うため、方向が一致しない場合があることを説明する。",
    prohibitedClaim: "endpoint間を共通単位で順位付けせず、直接測定された身体負荷と呼ばない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "model-limits", claimId: "COL-CLM-012", sourceIds: ["APP-SPEC-CURRENT", "APP-COL-LINTON", "APP-COL-VAN-HOOREN"],
    relatedInputs: ["全入力群", "欠測", "範囲外", "本人申告"], relatedRoutes: ["claim boundary", "unsupported-domain route", "information separation"], relatedRegions: ["12部位と別指標"],
    allowedClaim: "モデルの対応範囲、算出状態、非主張、本人入力との分離を説明する。",
    prohibitedClaim: "測定・診断・傷害確率・危険スコア・走行可否・因果推定を主張しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "training-progression-no-universal-rule", claimId: "COL-CLM-013", sourceIds: ["APP-COL-BUIST", "APP-COL-LINTON"],
    relatedInputs: ["予定距離", "予定時間", "予定と実績", "本人の振り返り"], relatedRoutes: ["general-knowledge column route", "plan non-prescription boundary"], relatedRegions: ["なし（走行全体の練習計画）"],
    allowedClaim: "一定割合の段階的プログラムを普遍的な傷害予防ルールとせず、予定と実績を分けて振り返る考え方を説明する。",
    prohibitedClaim: "安全な増加率、急増の許容、個人の傷害予防、最適な練習処方を提示しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "goals-and-recording-differ", claimId: "COL-CLM-014", sourceIds: ["APP-COL-KARAHANOGLU", "APP-COL-JANSSEN", "APP-COL-KRUKOWSKI"],
    relatedInputs: ["記録目的", "履歴", "本人メモ", "フィードバック表示"], relatedRoutes: ["general-knowledge column route", "running-goal reading route"], relatedRegions: ["なし（記録・目標の利用文脈）"],
    allowedClaim: "ランナーの目標・関心・技術利用が一様でなく、記録とフィードバックは本人の目的や時機に合わせて選べることを説明する。",
    prohibitedClaim: "記録継続、特定目標、利用者分類、このアプリによる行動変容の効果を保証しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "context-not-single-cause", claimId: "COL-CLM-015", sourceIds: ["APP-COL-LINTON", "APP-COL-WINTER", "APP-COL-BESOMI"],
    relatedInputs: ["天候・環境メモ", "睡眠・生活背景メモ", "本人の感じ方", "相談用メモ"], relatedRoutes: ["general-knowledge column route", "context-only information route", "consultation information-organization route"], relatedRegions: ["なし（複数の背景情報）"],
    allowedClaim: "複数の背景要因、経験差、研究上の予測限界を示し、一つの記録から原因を決めず事実を分けて残す考え方を説明する。",
    prohibitedClaim: "本人メモや数値から原因、診断、傷害確率、走行可否、個人予測を導かない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "cooldown-stretching-limits", claimId: "COL-CLM-016", sourceIds: ["APP-COL-COOLDOWN-VAN-HOOREN", "APP-COL-AFONSO"],
    relatedInputs: ["運動後に行ったこと", "ストレッチ記録", "本人の感じ方"], relatedRoutes: ["general-knowledge column route", "non-prescriptive after-run reading route"], relatedRegions: ["なし（運動後の一般的な振り返り）"],
    allowedClaim: "クールダウンと運動後ストレッチについて、確認された回復効果が限定的または一定せず、証拠にも限界があることを説明する。",
    prohibitedClaim: "実施方法・時間、治療効果、けが予防、回復保証、次の走行可否を提示しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "hydration-not-more-is-better", claimId: "COL-CLM-017", sourceIds: ["APP-COL-HEW-BUTLER"],
    relatedInputs: ["走行時間", "天候メモ", "食事・水分の自己記録"], relatedRoutes: ["general-knowledge column route", "non-diagnostic hydration reading route"], relatedRegions: ["なし（水分摂取の一般的な背景）"],
    allowedClaim: "水分摂取を量の多さだけで評価せず、飲み過ぎにも注意が必要という持久性運動の一般知識を説明する。",
    prohibitedClaim: "個人の必要量、脱水・低ナトリウム血症、電解質、治療、走行可否を判定または処方しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "post-run-food-timing-context", claimId: "COL-CLM-018", sourceIds: ["APP-COL-ARENT"],
    relatedInputs: ["運動内容", "次の運動までの間隔", "食事・水分の自己記録"], relatedRoutes: ["general-knowledge column route", "non-prescriptive nutrition reading route"], relatedRegions: ["なし（運動後の食事文脈）"],
    allowedClaim: "運動後の食事を一つの短い時間帯だけでなく、運動内容、頻度、次の運動までの間隔、一日の食事全体から捉える考え方を説明する。",
    prohibitedClaim: "食事量、食品、補助食品、摂取時刻、栄養状態、回復効果、走行可否を個別に評価または処方しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "sleep-not-hours-only", claimId: "COL-CLM-019", sourceIds: ["APP-COL-DOHERTY-SLEEP"],
    relatedInputs: ["睡眠の本人メモ", "睡眠時間", "本人の感じ方"], relatedRoutes: ["general-knowledge column route", "non-diagnostic sleep reading route"], relatedRegions: ["なし（睡眠と回復の一般的な背景）"],
    allowedClaim: "睡眠を一つの時間だけで正解とせず、時間、質、時機、本人の感じ方を分けて自己記録する考え方を説明する。",
    prohibitedClaim: "必要な睡眠時間、睡眠障害、回復状態、原因、次の走行可否を個人について判定または処方しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "heat-not-temperature-only", claimId: "COL-CLM-020", sourceIds: ["APP-COL-GRUNDSTEIN-HEAT", "APP-GUIDE-JSPO-HEAT"],
    relatedInputs: ["気温", "天候メモ", "時間帯", "走行ペース"], relatedRoutes: ["general-knowledge column route", "external current-information check boundary"], relatedRegions: ["なし（暑熱環境と走行全体の背景）"],
    allowedClaim: "暑さを一つの気温だけで決めず、WBGT、走る場所と時間、走行内容を分けて確認・記録する考え方を説明する。",
    prohibitedClaim: "熱中症、危険度、安全なペース、水分量、運動の中止・実施可否を個人について判定または処方しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "talk-test-as-subjective-cue", claimId: "COL-CLM-021", sourceIds: ["APP-COL-KWON-TALK"],
    relatedInputs: ["走行ペース", "会話のしやすさの本人メモ"], relatedRoutes: ["general-knowledge column route", "subjective talk-ease reading route"], relatedRegions: ["なし（走行全体の主観的な強さ）"],
    allowedClaim: "会話のしやすさを、速度とは別の主観的な手掛かりとして本人が記録・振り返る考え方を説明する。",
    prohibitedClaim: "会話のしやすさから、正確なペース、心肺機能、病気、安全な強さ、走行可否を評価または処方しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),

  articleRecord({
    articleId: "rof-j-how-to-read", claimId: "COL-CLM-022", sourceIds: ["APP-COL-ROF-2017", "APP-COL-ROF-J-2026"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "ROF-Jを主観的疲労の自己記録として説明し、同じ本人の前後・経時記録を振り返る考え方を示す。",
    prohibitedClaim: "疲労値から診断、回復状態、危険度、走行可否を判定しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "warmup-general", claimId: "COL-CLM-023", sourceIds: ["APP-GUIDE-MHLW-SAFE-2023", "APP-GUIDE-NHS-C25K"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "運動前に軽い動きから徐々に身体を動かす一般的な準備方法と、公開プログラムの例を紹介する。",
    prohibitedClaim: "特定の方法・時間を全員に処方せず、傷害予防効果を保証しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "pre-run-self-check", claimId: "COL-CLM-024", sourceIds: ["APP-GUIDE-MHLW-SAFE-2023", "APP-GUIDE-JSPO-HEAT"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "運動前に普段との体調差や暑熱環境を確認する一般的な観点を説明する。",
    prohibitedClaim: "アプリ独自に運動開始可否や診断を判定しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "stop-signs-during-run", claimId: "COL-CLM-025", sourceIds: ["APP-GUIDE-MHLW-SAFE-2023", "APP-GUIDE-MHLW-HEAT"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "公的資料に明記された運動中止サインと、症状を目標より優先する考え方を説明する。",
    prohibitedClaim: "症状から診断名・原因を推定せず、緊急対応を記事で代替しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "post-run-self-check", claimId: "COL-CLM-026", sourceIds: ["APP-GUIDE-MHLW-SAFE-2023", "APP-COL-ROF-J-2026"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "運動後に疲労感、身体の違和感、その他の体調変化を別々に確認・記録する考え方を説明する。",
    prohibitedClaim: "診断チェックリスト、回復判定、走行可否判定にしない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "pain-timing-and-persistence", claimId: "COL-CLM-027", sourceIds: ["APP-GUIDE-NHS-RUNNING-INJURIES", "APP-SPEC-CURRENT"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "痛みや違和感を発生時点、持続・悪化、腫れ等の事実に分けて記録し相談に備える考え方を説明する。",
    prohibitedClaim: "障害名や原因を推定しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "rest-days-and-recovery", claimId: "COL-CLM-028", sourceIds: ["APP-GUIDE-NHS-C25K", "APP-SPEC-CURRENT"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "初心者向け公開プログラムに休養日を置く例があることと、休養を未記録や失敗と同一視しない考え方を説明する。",
    prohibitedClaim: "休養日数・走行頻度を全員に処方しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "beginner-training-options", claimId: "COL-CLM-029", sourceIds: ["APP-GUIDE-NHS-C25K", "APP-GUIDE-ODPHP-PAG2", "APP-SPEC-CURRENT"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "初心者向けのrun/walk等の複数の練習方法と、少量から徐々に増やす一般原則を紹介する。",
    prohibitedClaim: "最適な練習メニューや安全な個人負荷を処方しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "run-walk-as-option", claimId: "COL-CLM-030", sourceIds: ["APP-GUIDE-NHS-C25K", "APP-SPEC-CURRENT"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "走行と歩行を交互にする方法が初心者向け公開プログラムで用いられることを紹介する。",
    prohibitedClaim: "連続走より安全・優れている、傷害を防ぐと主張しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "progression-over-weeks", claimId: "COL-CLM-031", sourceIds: ["APP-GUIDE-ODPHP-PAG2", "APP-GUIDE-NHS-C25K", "APP-COL-BUIST"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "固定期間や固定増加率を絶対視せず、徐々に活動量を増やし実績を振り返る考え方を説明する。",
    prohibitedClaim: "9週間・週3回・10%等を安全基準や達成期限にしない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "strength-and-cross-training", claimId: "COL-CLM-032", sourceIds: ["APP-GUIDE-MHLW-STRENGTH-2023", "APP-COL-STRENGTH-RUNNING-2024"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "有酸素活動と筋力トレーニングを組み合わせる一般的考え方とrunning economy研究の存在を紹介する。",
    prohibitedClaim: "初心者への筋トレ処方や傷害予防効果へ一般化しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "restart-after-break", claimId: "COL-CLM-033", sourceIds: ["APP-GUIDE-ODPHP-PAG2", "APP-GUIDE-MHLW-SAFE-2023"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "活動休止後に以前の量へ即復帰せず、現在の活動量から徐々に戻す一般原則を説明する。",
    prohibitedClaim: "疾病・傷害後の復帰時期や復帰プロトコルを処方しない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "injury-prevention-no-single-method", claimId: "COL-CLM-034", sourceIds: ["APP-COL-LINTON", "APP-COL-WINTER", "APP-COL-BESOMI"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "ランニング障害の多因子性と、単一方法を万能な予防策としない考え方を説明する。",
    prohibitedClaim: "個人の原因、傷害確率、万能な予防法を示さない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
  articleRecord({
    articleId: "seek-care-and-emergency-signs", claimId: "COL-CLM-035", sourceIds: ["APP-GUIDE-NHS-RUNNING-INJURIES", "APP-GUIDE-MHLW-SAFE-2023", "APP-GUIDE-MHLW-HEAT"],
    relatedInputs: [], relatedRoutes: ["general-knowledge reading route"], relatedRegions: ["なし（記事内容に応じた一般知識）"],
    allowedClaim: "公的・医療機関の一般情報に基づき、医療相談や救急を優先する代表的な場面を紹介する。",
    prohibitedClaim: "アプリ独自の受診判定・救急判定・診断を作らない。", reviewDate: EVIDENCE_GOVERNANCE_REVIEW_DATE,
  }),
]);

const ARTICLE_BY_ID = new Map(ARTICLE_EVIDENCE_REGISTRY.map((article) => [article.articleId, article]));

function getSourceEvidenceGovernance(sourceId) {
  return SOURCE_BY_ID.get(String(sourceId || "")) || null;
}

function getArticleEvidenceGovernance(articleId) {
  return ARTICLE_BY_ID.get(String(articleId || "")) || null;
}

function buildArticleEvidenceGovernance(articleId, sources = []) {
  const governance = getArticleEvidenceGovernance(articleId);
  if (!governance) return null;
  const declaredSourceIds = sources.map((source) => String(source?.sourceId || "")).filter(Boolean);
  const missingSourceIds = governance.sourceIds.filter((sourceId) => !declaredSourceIds.includes(sourceId));
  return Object.freeze({
    ...governance,
    version: EVIDENCE_GOVERNANCE_VERSION,
    sourceRecords: Object.freeze(governance.sourceIds.map(getSourceEvidenceGovernance).filter(Boolean)),
    sourceIntegrity: Object.freeze({
      declaredSourceIds: Object.freeze(declaredSourceIds),
      missingSourceIds: Object.freeze(missingSourceIds),
      status: missingSourceIds.length ? "MISMATCH" : "PASS",
    }),
  });
}
moduleExports["EVIDENCE_GOVERNANCE_VERSION"] = EVIDENCE_GOVERNANCE_VERSION;
moduleExports["EVIDENCE_GOVERNANCE_REVIEW_DATE"] = EVIDENCE_GOVERNANCE_REVIEW_DATE;
moduleExports["SOURCE_EVIDENCE_REGISTRY"] = SOURCE_EVIDENCE_REGISTRY;
moduleExports["ARTICLE_EVIDENCE_REGISTRY"] = ARTICLE_EVIDENCE_REGISTRY;
moduleExports["getSourceEvidenceGovernance"] = getSourceEvidenceGovernance;
moduleExports["getArticleEvidenceGovernance"] = getArticleEvidenceGovernance;
moduleExports["buildArticleEvidenceGovernance"] = buildArticleEvidenceGovernance;
internalModules.evidenceGovernanceData = moduleExports;
}
