import "./internal/content.js";
import { coreModules } from "./internal/moduleRegistry.js";

// Public core API used by the current application modules.
export const BODY_AREA_BY_ID = coreModules[28]["BODY_AREA_BY_ID"];
export const BODY_AREA_LATERALITY = coreModules[28]["BODY_AREA_LATERALITY"];
export const BODY_AREA_LATERALITY_LABELS = coreModules[28]["BODY_AREA_LATERALITY_LABELS"];
export const BODY_AREA_TAXONOMY = coreModules[28]["BODY_AREA_TAXONOMY"];
export const BODY_REGION_TERMINOLOGY = coreModules[57]["BODY_REGION_TERMINOLOGY"];
export const EQUIPMENT_TAG_OPTIONS = coreModules[7]["EQUIPMENT_TAG_OPTIONS"];
export const FOCUS_TAG_OPTIONS = coreModules[7]["FOCUS_TAG_OPTIONS"];
export const FOOT_PLACEMENT_OPTIONS = coreModules[7]["FOOT_PLACEMENT_OPTIONS"];
export const PRIMARY_REGIONAL_V2_MODEL_VERSION = coreModules[26]["PRIMARY_REGIONAL_V2_MODEL_VERSION"];
export const PRIMARY_REGIONAL_V2_REGION_DEFS = coreModules[25]["PRIMARY_REGIONAL_V2_REGION_DEFS"];
export const PROFILE_AGE_BAND_OPTIONS = coreModules[36]["PROFILE_AGE_BAND_OPTIONS"];
export const RHYTHM_STRIDE_OPTIONS = coreModules[7]["RHYTHM_STRIDE_OPTIONS"];
export const SAFETY_FLAG_KEYS = coreModules[29]["SAFETY_FLAG_KEYS"];
export const SHOE_SOFTNESS_OPTIONS = coreModules[7]["SHOE_SOFTNESS_OPTIONS"];
export const SHOE_TYPE_OPTIONS = coreModules[7]["SHOE_TYPE_OPTIONS"];
export const STORAGE_KEYS = coreModules[1]["STORAGE_KEYS"];
export const SURFACE_FIELDS = coreModules[3]["SURFACE_FIELDS"];
export const V27_COMMON_REGIONAL_GRADE_INPUT_MAX_PERCENT = coreModules[12]["V27_COMMON_REGIONAL_GRADE_INPUT_MAX_PERCENT"];
export const V27_EMPHASIS_REGION_IDS = coreModules[12]["V27_EMPHASIS_REGION_IDS"];
export const V27_REGIONS = coreModules[12]["V27_REGIONS"];
export const V27_TOTAL_GRADE_DOMAIN_MAX_PERCENT = coreModules[12]["V27_TOTAL_GRADE_DOMAIN_MAX_PERCENT"];
export const bodyRegionFamiliarName = coreModules[57]["bodyRegionFamiliarName"];
export const bodyRegionFormalName = coreModules[57]["bodyRegionFormalName"];
export const buildPrimaryRegionalV2ComparisonSignature = coreModules[26]["buildPrimaryRegionalV2ComparisonSignature"];
export const comparePrimaryRegionalV2Signatures = coreModules[26]["comparePrimaryRegionalV2Signatures"];
export const createApplicationServices = coreModules[59]["createApplicationServices"];
export const createHistoryWorkflow = coreModules[48]["createHistoryWorkflow"];
export const createMemoryStorage = coreModules[2]["createMemoryStorage"];
export const createPlanFactPreview = coreModules[49]["createPlanFactPreview"];
export const hasTreadmillOutdoorSurfaceMixFromComponents = coreModules[3]["hasTreadmillOutdoorSurfaceMixFromComponents"];
export const hasTreadmillOutdoorSurfaceMixFromCourse = coreModules[3]["hasTreadmillOutdoorSurfaceMixFromCourse"];
export const labelForOption = coreModules[7]["labelForOption"];
export const normalizeBodyAreaObservations = coreModules[28]["normalizeBodyAreaObservations"];
export const normalizeBodyProfile = coreModules[36]["normalizeBodyProfile"];
export const normalizePersonalContext = coreModules[7]["normalizePersonalContext"];
export const normalizePlanFactSession = coreModules[49]["normalizePlanFactSession"];
export const registerPwaServiceWorker = coreModules[0]["registerPwaServiceWorker"];
export const summarizePersonalContext = coreModules[7]["summarizePersonalContext"];
export const validateCoursePresetInput = coreModules[40]["validateCoursePresetInput"];