import { SURFACE_FIELDS } from "../core/appCore.js";
import { escapeHtml } from "../ui/commonComponents.js";
import { matchesMobileLayout } from "../ui/deviceLayout.js";
import { peekGpxCandidate } from "../ui/flowSessionState.js";
import { primarySurfaceSummary, slopeSummary } from "../ui/coursePresentation.js";

function safeReturnTo(context){const v=String(context?.parameters?.get("returnTo")||"#/record-input");return["#/record-input","#/plan","#/simulation"].some((p)=>v.startsWith(p))?v:"#/record-input";}
function returnLabel(returnTo=""){if(returnTo.startsWith("#/plan"))return"予定へ戻る";if(returnTo.startsWith("#/simulation"))return"シミュレーションへ戻る";return"今日の記録へ戻る";}
function selected(a,b){return String(a??"")===String(b)?" selected":"";}
function gradeMode(course={}){if(course.gradeInputMode==="SECTIONS"||(Array.isArray(course.sections)&&course.sections.length))return"SECTIONS";if(course.gradeKnowledge==="KNOWN_PROFILE")return"SUMMARY";if(course.gradeKnowledge==="KNOWN_FLAT")return"FLAT";return"UNKNOWN";}
function surfaceMode(course={}){const active=SURFACE_FIELDS.filter(({recordKey})=>Number(course[recordKey]||0)>0);if(!active.length)return"UNKNOWN";if(active.length===1&&Math.abs(Number(course[active[0].recordKey])-100)<.01)return"SINGLE";return"MIXED";}
function primarySurface(course={}){return[...SURFACE_FIELDS].sort((a,b)=>Number(course[b.recordKey]||0)-Number(course[a.recordKey]||0))[0]?.recordKey||"pavedPercent";}
function surfaceOptions(selectedKey=""){return SURFACE_FIELDS.map(({recordKey,label})=>`<option value="${escapeHtml(recordKey)}"${selected(selectedKey,recordKey)}>${escapeHtml(label)}</option>`).join("");}
function surfaceMix(course={}){return SURFACE_FIELDS.map(({recordKey,label})=>`<label class="mix-row"><span>${escapeHtml(label)}</span><span class="percent-control"><input name="${escapeHtml(recordKey)}" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course[recordKey]??0)}"><em>%</em></span></label>`).join("");}
function surfaceMixMobile(course={}){return SURFACE_FIELDS.map(({recordKey,label})=>`<label class="surface-mix-item"><span>${escapeHtml(label)}</span><span class="percent-control"><input name="${escapeHtml(recordKey)}" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course[recordKey]??0)}" aria-label="${escapeHtml(label)}の割合"><em>%</em></span></label>`).join("");}
function sectionRows(course={}){const sections=Array.isArray(course.sections)?course.sections:[];return Array.from({length:5},(_,i)=>{const item=sections[i]||{};const dir=item.gradeDirection||(Number(item.gradePercent)>0?"UPHILL":Number(item.gradePercent)<0?"DOWNHILL":"FLAT");return`<div class="section-row" data-course-section-row="${i}"><div class="section-row-head"><strong>区間 ${i+1}</strong></div><label class="section-field"><span>割合</span><span class="percent-control"><input name="sectionShare_${i}" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(item.sharePercent??"")}"><em>%</em></span></label><label class="section-field"><span>種類</span><select name="sectionDirection_${i}"><option value="UPHILL"${selected(dir,"UPHILL")}>上り</option><option value="FLAT"${selected(dir,"FLAT")}>平坦</option><option value="DOWNHILL"${selected(dir,"DOWNHILL")}>下り</option><option value="UNKNOWN"${selected(dir,"UNKNOWN")}>不明</option></select></label><label class="section-field section-grade"><span>坂の傾き（任意）</span><span class="percent-control"><input name="sectionGrade_${i}" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(Math.abs(Number(item.gradePercent||0))||"")}"><em>%</em></span></label></div>`;}).join("");}
function sectionRowsMobile(course={}){const sections=Array.isArray(course.sections)?course.sections:[];return Array.from({length:5},(_,i)=>{const item=sections[i]||{};const dir=item.gradeDirection||(Number(item.gradePercent)>0?"UPHILL":Number(item.gradePercent)<0?"DOWNHILL":"FLAT");return`<div class="course-section-row" data-course-section-row="${i}"><div class="course-section-row__head"><strong>区間 ${i+1}</strong><label><span>割合</span><span class="percent-control"><input name="sectionShare_${i}" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(item.sharePercent??"")}" aria-label="区間${i+1}の割合"><em>%</em></span></label></div><div class="course-section-row__fields"><label><span>種類</span><select name="sectionDirection_${i}"><option value="UPHILL"${selected(dir,"UPHILL")}>上り</option><option value="FLAT"${selected(dir,"FLAT")}>平坦</option><option value="DOWNHILL"${selected(dir,"DOWNHILL")}>下り</option><option value="UNKNOWN"${selected(dir,"UNKNOWN")}>不明</option></select></label><label><span>傾き <small>任意</small></span><span class="percent-control"><input name="sectionGrade_${i}" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(Math.abs(Number(item.gradePercent||0))||"")}" aria-label="区間${i+1}の坂の傾き"><em>%</em></span></label></div></div>`;}).join("");}
function mobileSlopeSummary(course={}){const gm=gradeMode(course);if(gm==="UNKNOWN")return"不明";if(gm==="FLAT")return"ほぼ平坦";return`上り ${Number(course.upPercent||0)}%・下り ${Number(course.downPercent||0)}%`;}
function mobileSurfaceSummary(course={}){const sm=surfaceMode(course);if(sm==="UNKNOWN")return"未設定";if(sm==="SINGLE"){const key=primarySurface(course);return SURFACE_FIELDS.find((item)=>item.recordKey===key)?.label||"1種類";}const active=SURFACE_FIELDS.map(({recordKey,label})=>({label,value:Number(course[recordKey]||0)})).filter((item)=>item.value>0).sort((a,b)=>b.value-a.value);if(!active.length)return"未入力";return active.length===1?active[0].label:`${active[0].label}ほか${active.length-1}種類`;}

function renderMobileCourseEditor({preset,gpxCandidate,course,returnTo,gm,sm,manager}){
  const profileMode=gm==="SUMMARY"||gm==="SECTIONS";
  return `<div class="screen screen--course-editor screen-layout screen-layout--course course-derived-screen course-mobile-v16"><div class="editor editor--derived course-derived-frame course-derived-frame--editor"><header class="editor-head course-derived-head"><a class="editor-back-link" href="${escapeHtml(manager)}">← コース設定</a><strong>${preset?"コースを編集":"新しいコース"}</strong><span aria-hidden="true"></span></header><main class="editor-main course-derived-body"><p class="course-mobile-lead">分かる項目だけ入力します。</p>${gpxCandidate?`<div class="gpx-prefill course-mobile-gpx-prefill"><strong>GPXの坂道候補を入力済み</strong><span>内容を確認して保存してください。</span></div>`:""}<form id="course-editor-form" novalidate><input type="hidden" name="courseId" value="${escapeHtml(preset?.id||"")}"><input type="hidden" name="returnTo" value="${escapeHtml(returnTo)}"><input type="hidden" name="fromGpx" value="${gpxCandidate?"1":"0"}"><input type="hidden" name="routePattern" value="${escapeHtml(course.routePattern||"UNKNOWN")}"><div class="form-messages" data-form-messages tabindex="-1" hidden></div>
  <section class="e-card course-mobile-card course-mobile-name"><div class="e-title"><b>1</b><div><small>必須</small><h2>コース名</h2></div></div><label class="field course-mobile-name-field"><span class="visually-hidden">コース名</span><input name="courseName" maxlength="80" required placeholder="例：川沿い往復" value="${escapeHtml(course.name||"")}"></label></section>
  <section class="e-card course-mobile-card course-mobile-grade"><div class="e-title"><b>2</b><div><small>分かる範囲で</small><h2>坂道</h2></div></div><select class="visually-hidden" name="gradeInputMode"><option value="UNKNOWN"${selected(gm,"UNKNOWN")}>分からない</option><option value="FLAT"${selected(gm,"FLAT")}>ほぼ平坦</option><option value="SUMMARY"${selected(gm,"SUMMARY")}>かんたん入力</option><option value="SECTIONS"${selected(gm,"SECTIONS")}>区間ごと</option></select><div class="mode course-grade-family" aria-label="坂道の状態"><button type="button" data-course-grade-family="UNKNOWN" class="${gm==="UNKNOWN"?"active":""}">不明</button><button type="button" data-course-grade-family="FLAT" class="${gm==="FLAT"?"active":""}">ほぼ平坦</button><button type="button" data-course-grade-family="PROFILE" class="${profileMode?"active":""}">坂あり</button></div><div class="course-grade-method" data-course-grade-method-panel${profileMode?"":" hidden"}><span>入力方法</span><div class="mode course-grade-method__toggle"><button type="button" data-course-grade-mode="SUMMARY" class="${gm==="SUMMARY"?"active":""}">かんたん</button><button type="button" data-course-grade-mode="SECTIONS" class="${gm==="SECTIONS"?"active":""}">区間ごと</button></div></div><div class="sub course-grade-summary" data-course-grade-summary${gm==="SUMMARY"?"":" hidden"}><div class="course-share-grid"><label class="mfield"><span>上り</span><div><input name="upPercent" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course.upPercent??0)}"><em>%</em></div></label><label class="mfield"><span>下り</span><div><input name="downPercent" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course.downPercent??0)}"><em>%</em></div></label></div><div class="easy-result"><div class="comp-head"><span>平坦</span><strong><output data-flat-share>—</output>%</strong></div></div><details class="course-grade-optional"><summary>坂の傾きも入力 <small>任意</small><i>⌄</i></summary><div class="course-grade-optional__grid"><label class="mfield"><span>上りの傾き</span><div><input name="upGradePercent" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(course.upGradePercent??"")}"><em>%</em></div></label><label class="mfield"><span>下りの傾き</span><div><input name="downGradePercent" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(course.downGradePercent??"")}"><em>%</em></div></label></div></details></div><div class="sub course-grade-sections" data-course-grade-sections${gm==="SECTIONS"?"":" hidden"}><div class="course-section-meta"><span>入力した区間の合計</span><strong><output data-section-share-total>0</output>%</strong></div><div class="section-rows">${sectionRowsMobile(course)}</div><button class="add-section" type="button" data-action="add-course-section">＋ 区間を追加</button><small class="course-section-limit">最大5区間</small></div></section>
  <section class="e-card course-mobile-card course-mobile-surface"><div class="e-title"><b>3</b><div><small>分かる範囲で</small><h2>路面</h2></div></div><select class="visually-hidden" name="surfaceInputMode"><option value="UNKNOWN"${selected(sm,"UNKNOWN")}>分からない</option><option value="SINGLE"${selected(sm,"SINGLE")}>1種類</option><option value="MIXED"${selected(sm,"MIXED")}>割合</option></select><div class="mode course-surface-mode"><button type="button" data-course-surface-mode="UNKNOWN" class="${sm==="UNKNOWN"?"active":""}">不明</button><button type="button" data-course-surface-mode="SINGLE" class="${sm==="SINGLE"?"active":""}">1種類</button><button type="button" data-course-surface-mode="MIXED" class="${sm==="MIXED"?"active":""}">割合</button></div><div class="sub course-surface-single" data-course-surface-single${sm==="SINGLE"?"":" hidden"}><label class="field"><span>主な路面</span><select name="primarySurfaceKey">${surfaceOptions(primarySurface(course))}</select></label></div><div class="sub course-surface-mixed" data-course-surface-mixed${sm==="MIXED"?"":" hidden"}><div class="comp-head"><span>路面構成</span><strong>合計 <output data-surface-share-total>0</output>%</strong></div><div class="surface-mix-grid">${surfaceMixMobile(course)}</div><p class="course-mobile-note">使った路面だけ入力。合計100%で保存します。</p></div></section>
  <section class="course-live-summary" aria-label="保存内容"><div class="course-live-summary__head"><span>保存内容</span><strong data-course-summary-name>${escapeHtml(course.name||"名称未入力")}</strong></div><div class="course-live-summary__facts"><span><small>坂道</small><b data-course-summary-grade>${escapeHtml(mobileSlopeSummary(course))}</b></span><span><small>路面</small><b data-course-summary-surface>${escapeHtml(mobileSurfaceSummary(course))}</b></span></div></section><div class="editor-actions course-mobile-actions"><button class="primary" type="submit">保存して使う</button></div></form></main></div></div>`;
}

function renderDesktopCourseEditor({preset,gpxCandidate,course,returnTo,gm,sm,manager}){
  return `<div class="screen screen--course-editor screen-layout screen-layout--course course-derived-screen"><div class="editor editor--derived course-derived-frame course-derived-frame--editor"><header class="editor-head course-derived-head"><a class="editor-back-link" href="${escapeHtml(returnTo)}">← ${escapeHtml(returnLabel(returnTo))}</a><strong>${preset?"コースを編集":"新しいコース"}</strong><a class="editor-manager-link" href="${escapeHtml(manager)}">コース一覧</a></header><main class="editor-main course-derived-body"><p class="eyebrow">COURSE EDITOR</p><h1>${preset?"コースを編集":"新しいコース"}</h1><p>分かる条件だけ入力します。不明は不明のまま残します。</p>${gpxCandidate?`<div class="gpx-prefill"><strong>ルートファイルの候補を入力しました</strong><span>上り・平坦・下りの候補を確認してから保存します。路面は推測しません。</span></div>`:""}<form id="course-editor-form" novalidate><input type="hidden" name="courseId" value="${escapeHtml(preset?.id||"")}"><input type="hidden" name="returnTo" value="${escapeHtml(returnTo)}"><input type="hidden" name="fromGpx" value="${gpxCandidate?"1":"0"}"><input type="hidden" name="routePattern" value="${escapeHtml(course.routePattern||"UNKNOWN")}"><div class="form-messages" data-form-messages tabindex="-1" hidden></div>
  <section class="e-card"><div class="e-title"><b>1</b><div><small>必須</small><h2>コース名</h2></div></div><label class="field"><span>コース名</span><input name="courseName" maxlength="80" required placeholder="例：川沿いの往復コース" value="${escapeHtml(course.name||"")}"></label></section>
  <section class="e-card"><div class="e-title"><b>2</b><div><small>分かる範囲で</small><h2>坂道</h2></div></div><select class="visually-hidden" name="gradeInputMode"><option value="UNKNOWN"${selected(gm,"UNKNOWN")}>分からない</option><option value="FLAT"${selected(gm,"FLAT")}>ほぼ平坦</option><option value="SUMMARY"${selected(gm,"SUMMARY")}>かんたん入力</option><option value="SECTIONS"${selected(gm,"SECTIONS")}>詳しく入力</option></select><div class="mode grade-mode"><button type="button" data-course-grade-mode="UNKNOWN" class="${gm==="UNKNOWN"?"active":""}">分からない</button><button type="button" data-course-grade-mode="FLAT" class="${gm==="FLAT"?"active":""}">ほぼ平坦</button><button type="button" data-course-grade-mode="SUMMARY" class="${gm==="SUMMARY"?"active":""}">かんたん入力</button><button type="button" data-course-grade-mode="SECTIONS" class="${gm==="SECTIONS"?"active":""}">詳しく入力</button></div><p class="note">坂の傾きが分からなくても構いません。不明な値は自動で推測しません。</p><div class="sub" data-course-grade-summary${gm==="SUMMARY"?"":" hidden"}><div class="support-title"><div><small>BEGINNER SUPPORT</small><strong>割合を入力</strong></div><span>坂の傾きは任意</span></div><div class="inputs"><label class="mfield"><span>上り</span><div><input name="upPercent" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course.upPercent??0)}"><em>%</em></div></label><label class="mfield"><span>下り</span><div><input name="downPercent" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course.downPercent??0)}"><em>%</em></div></label><label class="mfield"><span>上りの代表的な坂の傾き</span><div><input name="upGradePercent" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(course.upGradePercent??"")}"><em>%</em></div></label><label class="mfield"><span>下りの代表的な坂の傾き</span><div><input name="downGradePercent" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(course.downGradePercent??"")}"><em>%</em></div></label></div><div class="easy-result"><div class="comp-head"><span>自動計算した平坦割合</span><strong>平坦 <output data-flat-share>—</output>%</strong></div></div></div><div class="sub" data-course-grade-sections${gm==="SECTIONS"?"":" hidden"}><div class="support-title"><div><small>DETAIL</small><strong>区間ごとに入力</strong></div><span>最大5区間</span></div><p class="support-copy">区間の割合と種類を入力します。坂の傾きが分かる区間だけ数値を入力できます。</p><div class="section-rows">${sectionRows(course)}</div><button class="add-section" type="button" data-action="add-course-section">＋ 区間を追加</button><div class="section-summary">合計 <output data-section-share-total>0</output>%</div></div><a class="gpx-inline" href="#/gpx-analysis?returnTo=${encodeURIComponent(returnTo)}"><span><small>ファイルがある場合</small><strong>ルートファイル（GPX）から坂道を読み取る</strong></span><i>›</i></a></section>
  <section class="e-card"><div class="e-title"><b>3</b><div><small>分かる範囲で</small><h2>路面</h2></div></div><select class="visually-hidden" name="surfaceInputMode"><option value="UNKNOWN"${selected(sm,"UNKNOWN")}>分からない</option><option value="SINGLE"${selected(sm,"SINGLE")}>1種類</option><option value="MIXED"${selected(sm,"MIXED")}>割合で入力</option></select><div class="mode three"><button type="button" data-course-surface-mode="UNKNOWN" class="${sm==="UNKNOWN"?"active":""}">分からない</button><button type="button" data-course-surface-mode="SINGLE" class="${sm==="SINGLE"?"active":""}">1種類</button><button type="button" data-course-surface-mode="MIXED" class="${sm==="MIXED"?"active":""}">割合で入力</button></div><div class="sub" data-course-surface-single${sm==="SINGLE"?"":" hidden"}><span class="note">主な路面を選択</span><label class="field"><select name="primarySurfaceKey">${surfaceOptions(primarySurface(course))}</select></label></div><div class="sub" data-course-surface-mixed${sm==="MIXED"?"":" hidden"}><div class="comp-head"><span>路面構成</span><strong>合計 <output data-surface-share-total>0</output>%</strong></div><div class="mix">${surfaceMix(course)}</div><p class="note">使った路面だけ割合を入力し、合計を100%にします。</p></div></section>
  <section class="preview"><h2>このコースの要約</h2><strong>${escapeHtml(course.name||"コース名未入力")}</strong><div class="preview-grid"><div><small>坂道</small><span>${escapeHtml(slopeSummary(course))}</span></div><div><small>路面</small><span>${escapeHtml(primarySurfaceSummary(course))}</span></div></div></section><div class="editor-actions"><button class="primary" type="submit">保存してこのコースを使う</button></div></form></main></div></div>`;
}

export function renderCourseEditorScreen({services,context}){
  const id=String(context?.parameters?.get("id")||""); const preset=id?services.storage.courses.findById(id):null; const gpxCandidate=!preset&&context?.parameters?.get("gpx")==="1"?peekGpxCandidate()?.candidate:null; const course=preset?.course||gpxCandidate||{gradeKnowledge:"UNKNOWN",modelSurfaceClass:"UNKNOWN"}; const returnTo=safeReturnTo(context); const gm=gradeMode(course); const sm=surfaceMode(course); const manager=`#/course-library?returnTo=${encodeURIComponent(returnTo)}`;
  return matchesMobileLayout()?renderMobileCourseEditor({preset,gpxCandidate,course,returnTo,gm,sm,manager}):renderDesktopCourseEditor({preset,gpxCandidate,course,returnTo,gm,sm,manager});
}
