import { SURFACE_FIELDS } from "../core/runloadCore.js";
import { escapeHtml } from "../ui/commonComponents.js";
import { peekGpxCandidate } from "../ui/flowSessionState.js";
import { primarySurfaceSummary, slopeSummary } from "../ui/coursePresentation.js";

function safeReturnTo(context){const v=String(context?.parameters?.get("returnTo")||"#/record-input");return["#/record-input","#/plan","#/simulation"].some((p)=>v.startsWith(p))?v:"#/record-input";}
function selected(a,b){return String(a??"")===String(b)?" selected":"";}
function gradeMode(course={}){if(course.gradeInputMode==="SECTIONS"||(Array.isArray(course.sections)&&course.sections.length))return"SECTIONS";if(course.gradeKnowledge==="KNOWN_PROFILE")return"SUMMARY";if(course.gradeKnowledge==="KNOWN_FLAT")return"FLAT";return"UNKNOWN";}
function surfaceMode(course={}){const active=SURFACE_FIELDS.filter(({recordKey})=>Number(course[recordKey]||0)>0);if(!active.length)return"UNKNOWN";if(active.length===1&&Math.abs(Number(course[active[0].recordKey])-100)<.01)return"SINGLE";return"MIXED";}
function primarySurface(course={}){return[...SURFACE_FIELDS].sort((a,b)=>Number(course[b.recordKey]||0)-Number(course[a.recordKey]||0))[0]?.recordKey||"pavedPercent";}
function surfaceOptions(selectedKey=""){return SURFACE_FIELDS.map(({recordKey,label})=>`<option value="${escapeHtml(recordKey)}"${selected(selectedKey,recordKey)}>${escapeHtml(label)}</option>`).join("");}
function surfaceMix(course={}){return SURFACE_FIELDS.map(({recordKey,label})=>`<label class="mix-row"><span>${escapeHtml(label)}</span><input name="${escapeHtml(recordKey)}" type="number" min="0" max="100" step="1" value="${escapeHtml(course[recordKey]??0)}"></label>`).join("");}
function sectionRows(course={}){const sections=Array.isArray(course.sections)?course.sections:[];return Array.from({length:5},(_,i)=>{const item=sections[i]||{};const dir=item.gradeDirection||(Number(item.gradePercent)>0?"UPHILL":Number(item.gradePercent)<0?"DOWNHILL":"FLAT");return`<div class="section-row"><label><span>割合</span><input name="sectionShare_${i}" type="number" min="0" max="100" step="1" value="${escapeHtml(item.sharePercent??"")}"></label><label><span>種類</span><select name="sectionDirection_${i}"><option value="UPHILL"${selected(dir,"UPHILL")}>上り</option><option value="FLAT"${selected(dir,"FLAT")}>平坦</option><option value="DOWNHILL"${selected(dir,"DOWNHILL")}>下り</option><option value="UNKNOWN"${selected(dir,"UNKNOWN")}>不明</option></select></label><label><span>勾配%（任意）</span><input name="sectionGrade_${i}" type="number" min="0" max="100" step="0.1" value="${escapeHtml(Math.abs(Number(item.gradePercent||0))||"")}"></label></div>`;}).join("");}
export function renderCourseEditorScreen({services,context}){
  const id=String(context?.parameters?.get("id")||""); const preset=id?services.storage.courses.findById(id):null; const gpxCandidate=!preset&&context?.parameters?.get("gpx")==="1"?peekGpxCandidate()?.candidate:null; const course=preset?.course||gpxCandidate||{gradeKnowledge:"UNKNOWN",modelSurfaceClass:"UNKNOWN"}; const returnTo=safeReturnTo(context); const gm=gradeMode(course); const sm=surfaceMode(course); const manager=`#/course-library?returnTo=${encodeURIComponent(returnTo)}`;
  return `<div class="screen screen--course-editor prototype-parity prototype-parity--course"><div class="editor prototype-editor-route"><header class="editor-head"><a href="${escapeHtml(manager)}">‹ コース一覧</a><strong>${preset?"コースを編集":"新しいコース"}</strong><span></span></header><main class="editor-main"><p class="eyebrow">COURSE EDITOR</p><h1>${preset?"コースを編集":"新しいコース"}</h1><p>分かる条件だけ入力します。不明は不明のまま残します。</p>${gpxCandidate?`<div class="gpx-prefill"><strong>GPXの候補を入力しました</strong><span>上り・平坦・下りの候補を確認してから保存します。路面は推測しません。</span></div>`:""}<form id="course-editor-form" novalidate><input type="hidden" name="courseId" value="${escapeHtml(preset?.id||"")}"><input type="hidden" name="returnTo" value="${escapeHtml(returnTo)}"><input type="hidden" name="fromGpx" value="${gpxCandidate?"1":"0"}"><input type="hidden" name="routePattern" value="${escapeHtml(course.routePattern||"UNKNOWN")}"><div class="form-messages" data-form-messages tabindex="-1" hidden></div>
  <section class="e-card"><div class="e-title"><b>1</b><div><small>必須</small><h2>コース名</h2></div></div><label class="field"><span>コース名</span><input name="courseName" maxlength="80" required placeholder="例：川沿いの往復コース" value="${escapeHtml(course.name||"")}"></label></section>
  <section class="e-card"><div class="e-title"><b>2</b><div><small>分かる範囲で</small><h2>坂道</h2></div></div><select class="visually-hidden" name="gradeInputMode"><option value="UNKNOWN"${selected(gm,"UNKNOWN")}>分からない</option><option value="FLAT"${selected(gm,"FLAT")}>ほぼ平坦</option><option value="SUMMARY"${selected(gm,"SUMMARY")}>かんたん入力</option><option value="SECTIONS"${selected(gm,"SECTIONS")}>詳しく入力</option></select><div class="mode grade-mode"><button type="button" data-course-grade-mode="UNKNOWN" class="${gm==="UNKNOWN"?"active":""}">分からない</button><button type="button" data-course-grade-mode="FLAT" class="${gm==="FLAT"?"active":""}">ほぼ平坦</button><button type="button" data-course-grade-mode="SUMMARY" class="${gm==="SUMMARY"?"active":""}">かんたん入力</button><button type="button" data-course-grade-mode="SECTIONS" class="${gm==="SECTIONS"?"active":""}">詳しく入力</button></div><p class="note">勾配%が分からなくても構いません。不明な値は自動で推測しません。</p><div class="sub" data-course-grade-summary${gm==="SUMMARY"?"":" hidden"}><div class="support-title"><div><small>BEGINNER SUPPORT</small><strong>割合を入力</strong></div><span>勾配%は任意</span></div><div class="inputs"><label class="mfield"><span>上り</span><div><input name="upPercent" type="number" min="0" max="100" step="1" value="${escapeHtml(course.upPercent??0)}"><em>%</em></div></label><label class="mfield"><span>下り</span><div><input name="downPercent" type="number" min="0" max="100" step="1" value="${escapeHtml(course.downPercent??0)}"><em>%</em></div></label><label class="mfield"><span>上り代表勾配</span><div><input name="upGradePercent" type="number" min="0" max="100" step="0.1" value="${escapeHtml(course.upGradePercent??"")}"><em>%</em></div></label><label class="mfield"><span>下り代表勾配</span><div><input name="downGradePercent" type="number" min="0" max="100" step="0.1" value="${escapeHtml(course.downGradePercent??"")}"><em>%</em></div></label></div><div class="easy-result"><div class="comp-head"><span>自動計算した平坦割合</span><strong>平坦 <output data-flat-share>—</output>%</strong></div></div></div><div class="sub" data-course-grade-sections${gm==="SECTIONS"?"":" hidden"}><div class="support-title"><div><small>DETAIL</small><strong>区間ごとに入力</strong></div><span>最大5区間</span></div><p class="support-copy">区間の割合と種類を入力します。勾配が分かる区間だけ数値を入力できます。</p><div class="section-rows">${sectionRows(course)}</div><div class="section-summary">合計 <output data-section-share-total>0</output>%</div></div><a class="gpx-inline" href="#/gpx-analysis?returnTo=${encodeURIComponent(returnTo)}"><span><small>ファイルがある場合</small><strong>GPXから坂道を読み取る</strong></span><i>›</i></a></section>
  <section class="e-card"><div class="e-title"><b>3</b><div><small>分かる範囲で</small><h2>路面</h2></div></div><select class="visually-hidden" name="surfaceInputMode"><option value="UNKNOWN"${selected(sm,"UNKNOWN")}>分からない</option><option value="SINGLE"${selected(sm,"SINGLE")}>1種類</option><option value="MIXED"${selected(sm,"MIXED")}>割合で入力</option></select><div class="mode three"><button type="button" data-course-surface-mode="UNKNOWN" class="${sm==="UNKNOWN"?"active":""}">分からない</button><button type="button" data-course-surface-mode="SINGLE" class="${sm==="SINGLE"?"active":""}">1種類</button><button type="button" data-course-surface-mode="MIXED" class="${sm==="MIXED"?"active":""}">割合で入力</button></div><div class="sub" data-course-surface-single${sm==="SINGLE"?"":" hidden"}><span class="note">主な路面を選択</span><label class="field"><select name="primarySurfaceKey">${surfaceOptions(primarySurface(course))}</select></label></div><div class="sub" data-course-surface-mixed${sm==="MIXED"?"":" hidden"}><div class="comp-head"><span>路面構成</span><strong>合計 <output data-surface-share-total>0</output>%</strong></div><div class="mix">${surfaceMix(course)}</div><p class="note">使った路面だけ割合を入力し、合計を100%にします。</p></div></section>
  <section class="preview"><h2>このコースの要約</h2><strong>${escapeHtml(course.name||"コース名未入力")}</strong><div class="preview-grid"><div><small>坂道</small><span>${escapeHtml(slopeSummary(course))}</span></div><div><small>路面</small><span>${escapeHtml(primarySurfaceSummary(course))}</span></div></div></section><div class="editor-actions"><button class="primary" type="submit">保存してこのコースを使う</button></div></form></main></div></div>`;
}
