import { SURFACE_FIELDS } from "../../core/appCore.js";
import { escapeHtml } from "../../ui/commonComponents.js";
import { peekGpxCandidate } from "../../ui/flowSessionState.js";

function safeReturnTo(context){const v=String(context?.parameters?.get("returnTo")||"#/record-input");return["#/record-input","#/plan","#/simulation"].some((p)=>v.startsWith(p))?v:"#/record-input";}
export function returnLabel(returnTo=""){if(returnTo.startsWith("#/plan"))return"予定へ戻る";if(returnTo.startsWith("#/simulation"))return"シミュレーションへ戻る";return"今日の記録へ戻る";}
export function selected(a,b){return String(a??"")===String(b)?" selected":"";}
export function gradeMode(course={}){if(course.gradeInputMode==="SECTIONS"||(Array.isArray(course.sections)&&course.sections.length))return"SECTIONS";if(course.gradeKnowledge==="KNOWN_PROFILE")return"SUMMARY";if(course.gradeKnowledge==="KNOWN_FLAT")return"FLAT";return"UNKNOWN";}
export function surfaceMode(course={}){const active=SURFACE_FIELDS.filter(({recordKey})=>Number(course[recordKey]||0)>0);if(!active.length)return"UNKNOWN";if(active.length===1&&Math.abs(Number(course[active[0].recordKey])-100)<.01)return"SINGLE";return"MIXED";}
export function primarySurface(course={}){return[...SURFACE_FIELDS].sort((a,b)=>Number(course[b.recordKey]||0)-Number(course[a.recordKey]||0))[0]?.recordKey||"pavedPercent";}
export function surfaceOptions(selectedKey=""){return SURFACE_FIELDS.map(({recordKey,label})=>`<option value="${escapeHtml(recordKey)}"${selected(selectedKey,recordKey)}>${escapeHtml(label)}</option>`).join("");}
export function surfaceMix(course={}){return SURFACE_FIELDS.map(({recordKey,label})=>`<label class="mix-row"><span>${escapeHtml(label)}</span><span class="percent-control"><input name="${escapeHtml(recordKey)}" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course[recordKey]??0)}"><em>%</em></span></label>`).join("");}
export function surfaceMixCompact(course={}){return SURFACE_FIELDS.map(({recordKey,label})=>`<label class="surface-mix-item"><span>${escapeHtml(label)}</span><span class="percent-control"><input name="${escapeHtml(recordKey)}" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(course[recordKey]??0)}" aria-label="${escapeHtml(label)}の割合"><em>%</em></span></label>`).join("");}
export function sectionRows(course={}){const sections=Array.isArray(course.sections)?course.sections:[];return Array.from({length:5},(_,i)=>{const item=sections[i]||{};const dir=item.gradeDirection||(Number(item.gradePercent)>0?"UPHILL":Number(item.gradePercent)<0?"DOWNHILL":"FLAT");return`<div class="section-row" data-course-section-row="${i}"><div class="section-row-head"><strong>区間 ${i+1}</strong></div><label class="section-field"><span>割合</span><span class="percent-control"><input name="sectionShare_${i}" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(item.sharePercent??"")}"><em>%</em></span></label><label class="section-field"><span>種類</span><select name="sectionDirection_${i}"><option value="UPHILL"${selected(dir,"UPHILL")}>上り</option><option value="FLAT"${selected(dir,"FLAT")}>平坦</option><option value="DOWNHILL"${selected(dir,"DOWNHILL")}>下り</option><option value="UNKNOWN"${selected(dir,"UNKNOWN")}>不明</option></select></label><label class="section-field section-grade"><span>坂の傾き（任意）</span><span class="percent-control"><input name="sectionGrade_${i}" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(Math.abs(Number(item.gradePercent||0))||"")}"><em>%</em></span></label></div>`;}).join("");}
export function sectionRowsCompact(course={}){const sections=Array.isArray(course.sections)?course.sections:[];return Array.from({length:5},(_,i)=>{const item=sections[i]||{};const dir=item.gradeDirection||(Number(item.gradePercent)>0?"UPHILL":Number(item.gradePercent)<0?"DOWNHILL":"FLAT");return`<div class="course-section-row" data-course-section-row="${i}"><div class="course-section-row__head"><strong>区間 ${i+1}</strong><label><span>割合</span><span class="percent-control"><input name="sectionShare_${i}" type="number" inputmode="numeric" min="0" max="100" step="1" value="${escapeHtml(item.sharePercent??"")}" aria-label="区間${i+1}の割合"><em>%</em></span></label></div><div class="course-section-row__fields"><label><span>種類</span><select name="sectionDirection_${i}"><option value="UPHILL"${selected(dir,"UPHILL")}>上り</option><option value="FLAT"${selected(dir,"FLAT")}>平坦</option><option value="DOWNHILL"${selected(dir,"DOWNHILL")}>下り</option><option value="UNKNOWN"${selected(dir,"UNKNOWN")}>不明</option></select></label><label><span>傾き <small>任意</small></span><span class="percent-control"><input name="sectionGrade_${i}" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${escapeHtml(Math.abs(Number(item.gradePercent||0))||"")}" aria-label="区間${i+1}の坂の傾き"><em>%</em></span></label></div></div>`;}).join("");}
export function compactSlopeSummary(course={}){const gm=gradeMode(course);if(gm==="UNKNOWN")return"不明";if(gm==="FLAT")return"ほぼ平坦";return`上り ${Number(course.upPercent||0)}%・下り ${Number(course.downPercent||0)}%`;}
export function compactSurfaceSummary(course={}){const sm=surfaceMode(course);if(sm==="UNKNOWN")return"未設定";if(sm==="SINGLE"){const key=primarySurface(course);return SURFACE_FIELDS.find((item)=>item.recordKey===key)?.label||"1種類";}const active=SURFACE_FIELDS.map(({recordKey,label})=>({label,value:Number(course[recordKey]||0)})).filter((item)=>item.value>0).sort((a,b)=>b.value-a.value);if(!active.length)return"未入力";return active.length===1?active[0].label:`${active[0].label}ほか${active.length-1}種類`;}


export function prepareCourseEditorState({ services, context }) {
  const id = String(context?.parameters?.get("id") || "");
  const preset = id ? services.storage.courses.findById(id) : null;
  const gpxCandidate = !preset && context?.parameters?.get("gpx") === "1" ? peekGpxCandidate()?.candidate : null;
  const course = preset?.course || gpxCandidate || { gradeKnowledge: "UNKNOWN", modelSurfaceClass: "UNKNOWN" };
  const returnTo = safeReturnTo(context);
  const gm = gradeMode(course);
  const sm = surfaceMode(course);
  const manager = `#/course-library?returnTo=${encodeURIComponent(returnTo)}`;
  return Object.freeze({ preset, gpxCandidate, course, returnTo, gm, sm, manager });
}
